### PR TITLE
Delivering Customer Intelligence context to Ukraine, Kazakhstan and Emirates

### PR DESCRIPTION
**Pull request by maximpashuk**
@denisivan0v @rechkalov

---
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/78)

### CODE REVIEW

**Comment by denisivan0v** [comment]
Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build/project.json, line 7 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/78#-KHPwUqpVTi3j0wmmrLr:-KHPwUqpVTi3j0wmmrLs:-463864826) ([raw file](https://github.com/2gis/nuclear-river/blob/b20a430f9e40c15f16caef26a8b0e11df10f1d90/build/project.json#L7)):*
> ```JSON
>   "dependencies": {
>     "2GIS.NuClear.AdvancedSearch.Tools.ConvertTrackedUseCases": "0.1.11",
>     "2GIS.NuClear.BuildTools": "0.2.63-update-buildtool0006",
> ```

Будет же релизная версия?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/78)*

**Comment by denisivan0v** [comment]
@maximpashuk Can you rename the PR title to "Delivering Customer Intelligence context to Ukraine, Kazakhstan and Emirates"?

**Comment by rechkalov** [comment]
Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/78)*

**Comment by maximpashuk** [comment]
Done

<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> @maximpashuk Can you rename the PR title to "Delivering Customer Intelligence context to Ukraine, Kazakhstan and Emirates"?</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build/project.json, line 7 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/78#-KHPwUqpVTi3j0wmmrLr:-KHT9q457w_pbULWtIXq:349752878) ([raw file](https://github.com/2gis/nuclear-river/blob/b20a430f9e40c15f16caef26a8b0e11df10f1d90/build/project.json#L7)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Будет же релизная версия?</details>
Подвис pull request в buildtools (создан 19 апреля)
http://uk-tfs01.2gis.local/DefaultCollection/NuClear/_git/buildtools/pullrequest/1557

Иван никак не может посмотреть, а так бы уже давно была релизная версия.
Думаю, придётся пока релизнуться вот так, потом как иван посмотрит так заменим на стабильную.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/78#-:-KHT9f-KZyJr0qiS8AiX:676635175)*

**Pull request merged**
