### PR TITLE
Made possible to build release package versions & updated linq2db version

### PR DESCRIPTION
**Pull request by rechkalov**
@denisivan0v @maximpashuk

---
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/87)

### CODE REVIEW

**Comment by maximpashuk** [comment]
Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/87)*

**Comment by denisivan0v** [comment]
Reviewed 28 of 30 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[CustomerIntelligence/CustomerIntelligence.OperationsProcessing/app.config, line 1 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/87#-KI2DW0LmtsKViuvDESM:-KI2DW0LmtsKViuvDESN:-1191624750) ([raw file](https://github.com/2gis/nuclear-river/blob/2b28bc69e81826a126b5f9292cd934af6083a2fd/CustomerIntelligence/CustomerIntelligence.OperationsProcessing/app.config#L1)):*
> ```
> <?xml version="1.0" encoding="utf-8"?>
> ```

Удали плз

---

*[CustomerIntelligence/CustomerIntelligence.Replication/app.config, line 1 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/87#-KI2DvDkXMBinZQTF8pd:-KI2DvDkXMBinZQTF8pe:1099374578) ([raw file](https://github.com/2gis/nuclear-river/blob/2b28bc69e81826a126b5f9292cd934af6083a2fd/CustomerIntelligence/CustomerIntelligence.Replication/app.config#L1)):*
> ```
> <?xml version="1.0" encoding="utf-8"?>
> ```

удали плз

---

*[CustomerIntelligence/CustomerIntelligence.Storage/app.config, line 1 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/87#-KI2E7mhBMGTDi1wE5xF:-KI2E7mhBMGTDi1wE5xG:27109307) ([raw file](https://github.com/2gis/nuclear-river/blob/2b28bc69e81826a126b5f9292cd934af6083a2fd/CustomerIntelligence/CustomerIntelligence.Storage/app.config#L1)):*
> ```
> <?xml version="1.0" encoding="utf-8"?>
> ```

тоже можно удалить

---

*[Replication/Replication.OperationsProcessing/app.config, line 1 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/87#-KI2EIYwY0-2Exdq2c7K:-KI2EIYwY0-2Exdq2c7L:1099374578) ([raw file](https://github.com/2gis/nuclear-river/blob/2b28bc69e81826a126b5f9292cd934af6083a2fd/Replication/Replication.OperationsProcessing/app.config#L1)):*
> ```
> <?xml version="1.0" encoding="utf-8"?>
> ```

удали плз

---

*[StateInitialization/StateInitialization.Core/app.config, line 1 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/87#-KI2DnlDSp9koya01Z0p:-KI2DnlDSp9koya01Z0q:1099374578) ([raw file](https://github.com/2gis/nuclear-river/blob/2b28bc69e81826a126b5f9292cd934af6083a2fd/StateInitialization/StateInitialization.Core/app.config#L1)):*
> ```
> <?xml version="1.0" encoding="utf-8"?>
> ```

удали плз

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/87)*

**Comment by denisivan0v** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/2gis/nuclear-river/87#-KI2ElAj8ezHjhJnmOfw:-KI2ElAj8ezHjhJnmOfx:2097569914) (no related file):*
Давай еще сразу проапдейтим версию пакета Storage.LinqToDB

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/87)*

**Comment by denisivan0v** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/2gis/nuclear-river/87#-KI2ElAj8ezHjhJnmOfw:-KI2dN-h1li2_tmhEwtY:-1671097470) (no related file):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Давай еще сразу проапдейтим версию пакета Storage.LinqToDB
</details>
Storage packages v1.4.0 is out now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/87)*

**Comment by rechkalov** [comment]
Review status: 8 of 45 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/2gis/nuclear-river/87#-KI2ElAj8ezHjhJnmOfw:-KI7C9SDinEqNtg0PDxG:-517767086) (no related file):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Storage packages v1.4.0 is out now
</details>
2.0.1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/87)*

**Comment by denisivan0v** [comment]
Reviewed 37 of 41 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/87)*

**Comment by denisivan0v** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[CustomerIntelligence/CustomerIntelligence.Storage/app.config, line 1 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/87#-KI2E7mhBMGTDi1wE5xF:-KIBzEoPLm2rnkaoLkVZ:-864800557) ([raw file](https://github.com/2gis/nuclear-river/blob/2b28bc69e81826a126b5f9292cd934af6083a2fd/CustomerIntelligence/CustomerIntelligence.Storage/app.config#L1)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> тоже можно удалить
</details>
файл все же остался, хоть и пустой

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/87)*

**Comment by rechkalov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[CustomerIntelligence/CustomerIntelligence.Storage/app.config, line 1 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/87#-KI2E7mhBMGTDi1wE5xF:-KIRjOFLKZjonk-8TDbb:-1559490544) ([raw file](https://github.com/2gis/nuclear-river/blob/2b28bc69e81826a126b5f9292cd934af6083a2fd/CustomerIntelligence/CustomerIntelligence.Storage/app.config#L1)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> файл все же остался, хоть и пустой
</details>
Вероятно, глюк reviewable, в коммите этот файл помечен как удалённый
https://github.com/2gis/nuclear-river/pull/87/commits/75d3451ca30e506e83ecca3f114bcf451368584e

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/87)*

**Comment by denisivan0v** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[CustomerIntelligence/CustomerIntelligence.Storage/app.config, line 1 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/87#-KI2E7mhBMGTDi1wE5xF:-KIRlDOoddeG3ckEfzkI:961411061) ([raw file](https://github.com/2gis/nuclear-river/blob/2b28bc69e81826a126b5f9292cd934af6083a2fd/CustomerIntelligence/CustomerIntelligence.Storage/app.config#L1)):*
<details><summary><i>Previously, rechkalov (a.rechkalov) wrote…</i></summary>
> Вероятно, глюк reviewable, в коммите этот файл помечен как удалённый
> https://github.com/2gis/nuclear-river/pull/87/commits/75d3451ca30e506e83ecca3f114bcf451368584e
</details>
да, похоже на то

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/87)*

**Comment by maximpashuk** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/87)*

**Comment by denisivan0v** [comment]
Reviewed 1 of 30 files at r1, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/87)*

**Pull request merged**
