### PR TITLE
Доработал EqualityComparerFactory

### PR DESCRIPTION
**Pull request by rechkalov**
Добавил возможность использовать сторонние IEqualityComparer для сравнения полей.

---
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/142)

### CODE REVIEW

**Comment by denisivan0v** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Replication/Replication.Core/EqualityComparerFactory.cs, line 23 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/142#-KZ7HqSy-7MD8ZO3WXvY:-KZ7HqSy-7MD8ZO3WXvZ:bhoj3gb) ([raw file](https://github.com/2gis/nuclear-river/blob/e0f9204acb61d25501f3d46879f47a9e4dfce1e8/Replication/Replication.Core/EqualityComparerFactory.cs#L23)):*
> object[]

Нельзя использовать нетипизированный интерфейс `IEqualityComparer`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/142)*

**Comment by denisivan0v** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/142)*

**Comment by rechkalov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Replication/Replication.Core/EqualityComparerFactory.cs, line 23 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/142#-KZ7HqSy-7MD8ZO3WXvY:-KZPFqhgRxbUUAVNEL1c:b-bj9wh4) ([raw file](https://github.com/2gis/nuclear-river/blob/e0f9204acb61d25501f3d46879f47a9e4dfce1e8/Replication/Replication.Core/EqualityComparerFactory.cs#L23)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary><blockquote>

> object[]

Нельзя использовать нетипизированный интерфейс `IEqualityComparer`?
</blockquote></details>

Не стоит. А то его придётся реализовывать. А это довольно неоднозначный интерфейс. Если бы IEqualityComparer<T> наследовал от IEqualityComparer, то можно было бы. Но тогда бы встала опять проблема с его реализацией :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/142)*

**Comment by denisivan0v** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Replication/Replication.Core/EqualityComparerFactory.cs, line 23 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/142#-KZ7HqSy-7MD8ZO3WXvY:-Ka1hiWtu1TN5yIVwzRQ:b-3zq0jx) ([raw file](https://github.com/2gis/nuclear-river/blob/e0f9204acb61d25501f3d46879f47a9e4dfce1e8/Replication/Replication.Core/EqualityComparerFactory.cs#L23)):*
<details><summary><i>Previously, rechkalov (a.rechkalov) wrote…</i></summary><blockquote>

Не стоит. А то его придётся реализовывать. А это довольно неоднозначный интерфейс. Если бы IEqualityComparer<T> наследовал от IEqualityComparer, то можно было бы. Но тогда бы встала опять проблема с его реализацией :)
</blockquote></details>

Напиши тогда xml-коммент к конструкторам что ли. Важно как-то сообщить клиентам класса, что можно сюда передать объекты, реализующие  `IEqualityComparer<>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/142)*

**Comment by denisivan0v** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Replication/Replication.Core/EqualityComparerFactory.cs, line 27 at r2](https://reviewable.io:443/reviews/2gis/nuclear-river/142#-KbAdmik6cQkkRs5gNpP:-KbAdmiln0LCTv_8IeqJ:b-dtz3we) ([raw file](https://github.com/2gis/nuclear-river/blob/e30c425a4a438c88373791943985952ca4fc3525/Replication/Replication.Core/EqualityComparerFactory.cs#L27)):*
> пользовательнские

пользовательские

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/142)*

**Comment by denisivan0v** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/142)*

**Comment by denisivan0v** [comment]
Актуализируй бранч, гитхаб крестик показывает

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/142#-:-KbAdysQC2XS8Uy90rcL:b-xj21xa)*

**Comment by rechkalov** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Replication/Replication.Core/EqualityComparerFactory.cs, line 27 at r2](https://reviewable.io:443/reviews/2gis/nuclear-river/142#-KbAdmik6cQkkRs5gNpP:-KbDXIdcXIpNwtEtCI-J:b-896fix) ([raw file](https://github.com/2gis/nuclear-river/blob/e30c425a4a438c88373791943985952ca4fc3525/Replication/Replication.Core/EqualityComparerFactory.cs#L27)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary><blockquote>

> пользовательнские

пользовательские
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/142)*

**Comment by rechkalov** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Replication/Replication.Core/EqualityComparerFactory.cs, line 27 at r2](https://reviewable.io:443/reviews/2gis/nuclear-river/142#-KbAdmik6cQkkRs5gNpP:-KbDYiFPYztZ_WN6NjF2:b32w0x) ([raw file](https://github.com/2gis/nuclear-river/blob/e30c425a4a438c88373791943985952ca4fc3525/Replication/Replication.Core/EqualityComparerFactory.cs#L27)):*
<details><summary><i>Previously, rechkalov (a.rechkalov) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/142)*

**Comment by denisivan0v** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/142)*

**Pull request merged**
