### PR TITLE
Moved to service bus transport for messages between processing stages

### PR DESCRIPTION
**Pull request by rechkalov**
@denisivan0v @maximpashuk

---
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/84)

### CODE REVIEW

**Comment by maximpashuk** [comment]
Reviewed 16 of 31 files at r1, 29 of 32 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Transports/XmlEventSerializer.cs, line 41 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KI2Q6x83xmPzPqyVU8E:-KI2Q6x83xmPzPqyVU8F:1381733744) ([raw file](https://github.com/2gis/nuclear-river/blob/44726e71dd0c2275052231d0b651a17e2bb59c13/CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Transports/XmlEventSerializer.cs#L41)):*
> ```Smalltalk
>                 if (dataObjectType != null && dataObjectId != null)
>                 {
>                     return new DataObjectCreatedEvent(ResolveDataObjectType(dataObjectType.Value), (long)dataObjectId, DateTime.Parse(eventTime.Value));
> ```

Вместо DateTime.Parse предлагаю использовать explicit operator DateTime (у XAttribute).
Ниже же тебя не смущает просто так отдать @event.Time в конструктор XAttribute без явного ToString().
Тут надо либо полностью отдавать на откуп сериализацию либо всё делать самим, а сейчас половина на половину.

---

*[Replication/Replication.OperationsProcessing/Transports/SQLStore/SqlStoreReceiver.cs, line 1 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KI2_TjbQp1gkresR5sy:-KI2_TjcxhaLUguxA8iS:1645300579) ([raw file](https://github.com/2gis/nuclear-river/blob/44726e71dd0c2275052231d0b651a17e2bb59c13/Replication/Replication.OperationsProcessing/Transports/SQLStore/SqlStoreReceiver.cs#L1)):*
> ```Smalltalk
> using System;
> ```

Раз теперь всё на service bus, предлагаю безжалостно выпилить всю папку SQLStore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/84)*

**Comment by rechkalov** [comment]
Review status: 43 of 44 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Transports/XmlEventSerializer.cs, line 41 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KI2Q6x83xmPzPqyVU8E:-KIRSvXIDMKBY07Zu9Ia:46313981) ([raw file](https://github.com/2gis/nuclear-river/blob/44726e71dd0c2275052231d0b651a17e2bb59c13/CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Transports/XmlEventSerializer.cs#L41)):*
<details><summary><i>Previously, maximpashuk (Maxim Pashuk) wrote…</i></summary>
> Вместо DateTime.Parse предлагаю использовать explicit operator DateTime (у XAttribute).
> Ниже же тебя не смущает просто так отдать @event.Time в конструктор XAttribute без явного ToString().
> Тут надо либо полностью отдавать на откуп сериализацию либо всё делать самим, а сейчас половина на половину.
</details>
Согласен, сглупил.

---

*[Replication/Replication.OperationsProcessing/Transports/SQLStore/SqlStoreReceiver.cs, line 1 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KI2_TjbQp1gkresR5sy:-KIRY49KJAQc2rRRM9o9:-1831305785) ([raw file](https://github.com/2gis/nuclear-river/blob/44726e71dd0c2275052231d0b651a17e2bb59c13/Replication/Replication.OperationsProcessing/Transports/SQLStore/SqlStoreReceiver.cs#L1)):*
<details><summary><i>Previously, maximpashuk (Maxim Pashuk) wrote…</i></summary>
> Раз теперь всё на service bus, предлагаю безжалостно выпилить всю папку SQLStore.
</details>
Э, не, на service bus пока только один контекст. Если переведём VR, всё равно останется как минимум телефония. Думаю, стоит оставить для тех, кто пока не планирует переезжать на него.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/84)*

**Comment by maximpashuk** [comment]
Reviewed 1 of 31 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/84)*

**Comment by denisivan0v** [comment]
Reviewed 3 of 32 files at r1, 26 of 30 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[CustomerIntelligence/CustomerIntelligence.Replication.Host/Factories/EventLoggingStrategyProvider.cs, line 20 \[r5\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KIaovwSrR6vKDrJJwJ0:-KIaovwSrR6vKDrJJwJ1:-1569084007) ([raw file](https://github.com/2gis/nuclear-river/blob/d9b6aed38fda7b23d7092999c90769269f875cac/CustomerIntelligence/CustomerIntelligence.Replication.Host/Factories/EventLoggingStrategyProvider.cs#L20)):*
> ```Smalltalk
> namespace NuClear.CustomerIntelligence.Replication.Host.Factories
> {
>     public sealed class EventLoggingStrategyProvider : IEventLoggingStrategyProvider
> ```

UnityEventLoggingStrategyProvider

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectCreatedEvent.cs, line 18 \[r5\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KIao-NminwfNh8rWuO8:-KIao-NminwfNh8rWuO9:-1065550220) ([raw file](https://github.com/2gis/nuclear-river/blob/d9b6aed38fda7b23d7092999c90769269f875cac/CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectCreatedEvent.cs#L18)):*
> ```Smalltalk
>             DataObjectType = dataObjectType;
>             DataObjectId = dataObjectId;
>             Time = eventTime;
> ```

Переименуем в HappenedTime или EventHappenedTime?

---

*[Replication/Replication.OperationsProcessing/Transports/EventLoggingStrategyDecorator.cs, line 25 \[r5\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KIaoX2DfhjYMdLctMAZ:-KIaoX2DfhjYMdLctMA_:-1778163622) ([raw file](https://github.com/2gis/nuclear-river/blob/d9b6aed38fda7b23d7092999c90769269f875cac/Replication/Replication.OperationsProcessing/Transports/EventLoggingStrategyDecorator.cs#L25)):*
> ```Smalltalk
>         public bool TryLog(IReadOnlyCollection<TEvent> events, out string report)
>         {
>             using (Probe.Create("Send events"))
> ```

Log events

---

*[Replication/Replication.OperationsProcessing/Transports/ServiceBus/Event2BrokeredMessageConverter.cs, line 8 \[r5\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KIaohRxJLyXtuVCGIFA:-KIaohRxJLyXtuVCGIFB:-1292152038) ([raw file](https://github.com/2gis/nuclear-river/blob/d9b6aed38fda7b23d7092999c90769269f875cac/Replication/Replication.OperationsProcessing/Transports/ServiceBus/Event2BrokeredMessageConverter.cs#L8)):*
> ```Smalltalk
> namespace NuClear.Replication.OperationsProcessing.Transports.ServiceBus
> {
>     public sealed class Event2BrokeredMessageConverter : IEvent2BrokeredMessageConverter<IEvent>
> ```

Давай всю логику сериализатора сюда переместим? Зачем он нам отдельно?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/84)*

**Comment by maximpashuk** [comment]
Reviewed 26 of 30 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[CustomerIntelligence/CustomerIntelligence.Replication.Host/Factories/EventLoggingStrategyProvider.cs, line 50 \[r5\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KIbO7coj-TvbMeB4GmC:-KIbO7cpIsccC8nwLnA-:67599223) ([raw file](https://github.com/2gis/nuclear-river/blob/d9b6aed38fda7b23d7092999c90769269f875cac/CustomerIntelligence/CustomerIntelligence.Replication.Host/Factories/EventLoggingStrategyProvider.cs#L50)):*
> ```Smalltalk
>         private IEventLoggingStrategy<TEvent> DecorateStrategy<TEvent>(IEventLoggingStrategy<TEvent> strategy, IMessageFlow flow)
>         {
>             return new EventLoggingStrategyDecorator<TEvent>(strategy, CreateFilter<TEvent>(flow), CreateReporter(flow));
> ```

Я предлагаю прямо здесь в зависимости от flow создавать один либо другой Decorator, в методах CreateFilter и CreateReporter одни и те же if по одним и тем же flow.
Раз уж они одни и те же, то можно прямо сюда прописать один раз этот if.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/84)*

**Comment by maximpashuk** [comment]
Reviewed 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/84)*

**Comment by rechkalov** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[CustomerIntelligence/CustomerIntelligence.Replication.Host/Factories/EventLoggingStrategyProvider.cs, line 20 \[r5\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KIaovwSrR6vKDrJJwJ0:-KJJsSy2cFh88KgjjPr2:5205889) ([raw file](https://github.com/2gis/nuclear-river/blob/d9b6aed38fda7b23d7092999c90769269f875cac/CustomerIntelligence/CustomerIntelligence.Replication.Host/Factories/EventLoggingStrategyProvider.cs#L20)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> UnityEventLoggingStrategyProvider
</details>
ок

---

*[CustomerIntelligence/CustomerIntelligence.Replication.Host/Factories/EventLoggingStrategyProvider.cs, line 50 \[r5\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KIbO7coj-TvbMeB4GmC:-KJJsrndv02znmjczFAN:1014780454) ([raw file](https://github.com/2gis/nuclear-river/blob/d9b6aed38fda7b23d7092999c90769269f875cac/CustomerIntelligence/CustomerIntelligence.Replication.Host/Factories/EventLoggingStrategyProvider.cs#L50)):*
<details><summary><i>Previously, maximpashuk (Maxim Pashuk) wrote…</i></summary>
> Я предлагаю прямо здесь в зависимости от flow создавать один либо другой Decorator, в методах CreateFilter и CreateReporter одни и те же if по одним и тем же flow.
> Раз уж они одни и те же, то можно прямо сюда прописать один раз этот if.
</details>
Сделал немного иначе, но не хуже. Только помоги дать имя новому интерфейсу.

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectCreatedEvent.cs, line 18 \[r5\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KIao-NminwfNh8rWuO8:-KJJrE-7RrdAhIXukG5z:5205889) ([raw file](https://github.com/2gis/nuclear-river/blob/d9b6aed38fda7b23d7092999c90769269f875cac/CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectCreatedEvent.cs#L18)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Переименуем в HappenedTime или EventHappenedTime?
</details>
ок

---

*[Replication/Replication.OperationsProcessing/Transports/EventLoggingStrategyDecorator.cs, line 25 \[r5\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KIaoX2DfhjYMdLctMAZ:-KJJrpjzxcpAlWEoATW-:5205889) ([raw file](https://github.com/2gis/nuclear-river/blob/d9b6aed38fda7b23d7092999c90769269f875cac/Replication/Replication.OperationsProcessing/Transports/EventLoggingStrategyDecorator.cs#L25)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Log events
</details>
ок

---

*[Replication/Replication.OperationsProcessing/Transports/ServiceBus/Event2BrokeredMessageConverter.cs, line 8 \[r5\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KIaohRxJLyXtuVCGIFA:-KJJqRCECjk9_pBgcyxW:40428336) ([raw file](https://github.com/2gis/nuclear-river/blob/d9b6aed38fda7b23d7092999c90769269f875cac/Replication/Replication.OperationsProcessing/Transports/ServiceBus/Event2BrokeredMessageConverter.cs#L8)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Давай всю логику сериализатора сюда переместим? Зачем он нам отдельно?
</details>
1. Потому что XElement не обязательно упаковывать в BrokeredMessage. Я всё-таки надеюсь, что мы когда-нибудь допилим и sql транспорт до этого уровня.
2. Потому что этот конвертер является общим библиотечным классом, а сериализатор - специфичен для контекста.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/84)*

**Comment by maximpashuk** [comment]
Reviewed 1 of 32 files at r1, 12 of 16 files at r7, 11 of 11 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/84)*

**Comment by denisivan0v** [comment]
Reviewed 10 of 32 files at r1, 10 of 32 files at r2, 1 of 1 files at r3, 4 of 30 files at r5, 2 of 6 files at r6, 11 of 16 files at r7, 11 of 11 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Replication/Replication.OperationsProcessing/Transports/ServiceBus/BrokeredMessage2EventMessageTransformer.cs, line 15 \[r8\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KKmwvs9kW1hIdhUWn_a:-KKmwvsAhCt5ms18ASN2:664190988) ([raw file](https://github.com/2gis/nuclear-river/blob/c8149a542e25186135bc4c638dddbc1f4925d0a6/Replication/Replication.OperationsProcessing/Transports/ServiceBus/BrokeredMessage2EventMessageTransformer.cs#L15)):*
> ```Smalltalk
>         private readonly IXmlEventSerializer _eventSerializer;
> 
>         public BrokeredMessage2EventMessageTransformer(IXmlEventSerializer eventSerializer)
> ```

Нужна ли в этом случае абстракция `IXmlEventSerializer`? Можно в xml сериализовывать/десеризлвывать прямо внутри этого класса

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/84)*

**Comment by rechkalov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Replication/Replication.OperationsProcessing/Transports/ServiceBus/BrokeredMessage2EventMessageTransformer.cs, line 15 \[r8\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KKmwvs9kW1hIdhUWn_a:-KKn0At-V8xfauXpmOOq:-1102504633) ([raw file](https://github.com/2gis/nuclear-river/blob/c8149a542e25186135bc4c638dddbc1f4925d0a6/Replication/Replication.OperationsProcessing/Transports/ServiceBus/BrokeredMessage2EventMessageTransformer.cs#L15)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Нужна ли в этом случае абстракция `IXmlEventSerializer`? Можно в xml сериализовывать/десеризлвывать прямо внутри этого класса
</details>
Нужна, поскольку сериализация контекстно-специфична, а этот класс не входит в контекст.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/84)*

**Comment by denisivan0v** [comment]
Reviewed 1 of 32 files at r1, 2 of 32 files at r2, 14 of 19 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Commands/RecordDelayCommand.cs, line 14 \[r9\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KKvg1M-a9UstTyiQjLe:-KKvg1M-a9UstTyiQjLf:-1858396099) ([raw file](https://github.com/2gis/nuclear-river/blob/1766c4d2e7f8ce2dbe6ce79046cdadbb5c771b30/CustomerIntelligence/CustomerIntelligence.Replication/Commands/RecordDelayCommand.cs#L14)):*
> ```Smalltalk
>         }
> 
>         public DateTime EventTime { get; }
> ```

Может UtcDateTime или просто UtcDate?

---

*[Replication/Replication.OperationsProcessing/Transports/ServiceBus/BrokeredMessage2EventMessageTransformer.cs, line 15 \[r8\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KKmwvs9kW1hIdhUWn_a:-KKvh1hqDpnTLjY7zi_q:1902956748) ([raw file](https://github.com/2gis/nuclear-river/blob/c8149a542e25186135bc4c638dddbc1f4925d0a6/Replication/Replication.OperationsProcessing/Transports/ServiceBus/BrokeredMessage2EventMessageTransformer.cs#L15)):*
<details><summary><i>Previously, rechkalov (a.rechkalov) wrote…</i></summary>
> Нужна, поскольку сериализация контекстно-специфична, а этот класс не входит в контекст.
</details>
Может нам не нужен такой библиотечный класс, который ничего не делает и перевызывает сериализатор? Он использован в PrimaryMessageTransformerResolveStrategy, который контекстно-специфичный.

Кроме того, немного смущает xml в названии IXmlEventSerializer, хотя у нас нет требований использовать именно xml.

В общем, я считаю, что можно оставить все эти детали на уровне контекста, т.к. на уровне платформы есть IMessageTransformerResolveStrategy, которой достаточно

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/84)*

**Comment by rechkalov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Commands/RecordDelayCommand.cs, line 14 \[r9\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KKvg1M-a9UstTyiQjLe:-KKvk4TydA_AgBblLBio:1871563823) ([raw file](https://github.com/2gis/nuclear-river/blob/1766c4d2e7f8ce2dbe6ce79046cdadbb5c771b30/CustomerIntelligence/CustomerIntelligence.Replication/Commands/RecordDelayCommand.cs#L14)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Может UtcDateTime или просто UtcDate?
</details>
Зачем? Других и не бывает.

---

*[Replication/Replication.OperationsProcessing/Transports/ServiceBus/BrokeredMessage2EventMessageTransformer.cs, line 15 \[r8\]](https://reviewable.io:443/reviews/2gis/nuclear-river/84#-KKmwvs9kW1hIdhUWn_a:-KKvkIlxQjv2aeLjhTv3:1987148236) ([raw file](https://github.com/2gis/nuclear-river/blob/c8149a542e25186135bc4c638dddbc1f4925d0a6/Replication/Replication.OperationsProcessing/Transports/ServiceBus/BrokeredMessage2EventMessageTransformer.cs#L15)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Может нам не нужен такой библиотечный класс, который ничего не делает и перевызывает сериализатор? Он использован в PrimaryMessageTransformerResolveStrategy, который контекстно-специфичный.
> 
> Кроме того, немного смущает xml в названии IXmlEventSerializer, хотя у нас нет требований использовать именно xml.
> 
> В общем, я считаю, что можно оставить все эти детали на уровне контекста, т.к. на уровне платформы есть IMessageTransformerResolveStrategy, которой достаточно
</details>
Он нужен, ибо часть конвейера OperationProcessing. Согласись, неразумно в контекст тащить знания о нём.

Xml на месте, поскольку этот трансформатор - часть контракта (отправка + получения) которые договорились использовать именно xml. Т.е. если нужен не xml - нужен другой MessageTransformerBase

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/84)*

**Comment by denisivan0v** [comment]
Reviewed 4 of 4 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/84)*

**Pull request merged**
