### PR TITLE
Fixed Balance recalculation bug

### PR DESCRIPTION
**Pull request by rechkalov**
Балансы у фирмы хранятся по всем городам, 
события на пересчёт генерировались только по городу лицевого счёта.

---
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/106)

### CODE REVIEW

**Comment by maximpashuk** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs, line 48 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/106#-KKJAm6V__yjxb_qFqI5:-KKJAm6V__yjxb_qFqI6:1538448789) ([raw file](https://github.com/2gis/nuclear-river/blob/714342709823ccad7984dd03f6b0757e1015ad6f/CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs#L48)):*
> ```Smalltalk
>                            join client in _query.For<Client>() on legalPerson.ClientId equals client.Id
>                            join branchOfficeOrganizationUnit in _query.For<BranchOfficeOrganizationUnit>()
>                                on account.BranchOfficeOrganizationUnitId equals branchOfficeOrganizationUnit.Id
> ```

Я возможно чего-то не понимаю, но по-моему join с BranchOfficeOrganuzationUnit тоже тогда не имеет смысла.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/106)*

**Comment by denisivan0v** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs, line 48 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/106#-KKJAm6V__yjxb_qFqI5:-KKJciKG9KgyNnORWdm7:-1339171957) ([raw file](https://github.com/2gis/nuclear-river/blob/714342709823ccad7984dd03f6b0757e1015ad6f/CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs#L48)):*
<details><summary><i>Previously, maximpashuk (Maxim Pashuk) wrote…</i></summary>
> Я возможно чего-то не понимаю, но по-моему join с BranchOfficeOrganuzationUnit тоже тогда не имеет смысла.
</details>
Получается, что мы сейчас считаем протухшими все лицевые счета юр лица клиента. В этом случае, да, юр лицо отделения организации ни при чем

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs, line 49 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/106#-KKJdOMKzDZRdPbosMxD:-KKJdOMKzDZRdPbosMxE:315585129) ([raw file](https://github.com/2gis/nuclear-river/blob/714342709823ccad7984dd03f6b0757e1015ad6f/CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs#L49)):*
> ```Smalltalk
>                            join branchOfficeOrganizationUnit in _query.For<BranchOfficeOrganizationUnit>()
>                                on account.BranchOfficeOrganizationUnitId equals branchOfficeOrganizationUnit.Id
>                            join firm in _query.For<Firm>() on client.Id equals firm.ClientId
> ```

тут можно сразу legalPerson.ClientId == firm.ClientId без джойна с клиентами

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/106)*

**Comment by rechkalov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs, line 48 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/106#-KKJAm6V__yjxb_qFqI5:-KKJBSBaeNAsLsqMuLt6:1513227059) ([raw file](https://github.com/2gis/nuclear-river/blob/714342709823ccad7984dd03f6b0757e1015ad6f/CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs#L48)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Получается, что мы сейчас считаем протухшими все лицевые счета юр лица клиента. В этом случае, да, юр лицо отделения организации ни при чем
</details>
Да, это я взял лишку из FirmBalance.

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs, line 49 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/106#-KKJdOMKzDZRdPbosMxD:-KKMpeMt_uRDGyxRYAkG:1513227059) ([raw file](https://github.com/2gis/nuclear-river/blob/714342709823ccad7984dd03f6b0757e1015ad6f/CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs#L49)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> тут можно сразу legalPerson.ClientId == firm.ClientId без джойна с клиентами
</details>
Да, это я взял лишку из FirmBalance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/106)*

**Comment by denisivan0v** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/106)*

**Pull request merged**
