### PR TITLE
Querying component separated from the host

### LINKED ISSUE #35: Decouple Querying component infrastructure and the WebAPI host
As the result we'll be able to reference Querying component as nupkg in different hosts

### PR DESCRIPTION
**Pull request by denisivan0v**
closes #35

---
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/51)

### CODE REVIEW

**Comment by denisivan0v** [comment]
ping @maximpashuk @rechkalov

**Comment by rechkalov** [comment]
Review status: 0 of 176 files reviewed at latest revision, 4 unresolved discussions.

---

*[CustomerIntelligence/CustomerIntelligence.Querying.Host/Properties/AssemblyInfo.cs, line 7 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/51#-KDTGgLT6Hq7rqyOtyvq:-KDTGgLUjOyWMJSC4Lj_:-1520858481) ([raw file](https://github.com/2gis/nuclear-river/blob/e1f5922c0df19be9c2a9ca08d521302c82223b67/CustomerIntelligence/CustomerIntelligence.Querying.Host/Properties/AssemblyInfo.cs#L7)):*
Стоит актуализировать имена

---

*[CustomerIntelligence/CustomerIntelligence.Querying.Host/QueryBuilder/Content/odata-query-builder.css, line 1 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/51#-KDTGxpwtECCYz16PpLz:-KDTGxpwtECCYz16PpM-:-349388007) ([raw file](https://github.com/2gis/nuclear-river/blob/e1f5922c0df19be9c2a9ca08d521302c82223b67/CustomerIntelligence/CustomerIntelligence.Querying.Host/QueryBuilder/Content/odata-query-builder.css#L1)):*
Файлы из каталога QueryBuilder (*.js, *.css, *.gif, *.html)  было бы неплохо оставить в общем пакете.

---

*[Querying/Querying.Edm/Properties/AssemblyInfo.cs, line 7 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/51#-KDTMt_m98cLqrQlYI89:-KDTMt_nVEDZyBDBlYks:-1181461127) ([raw file](https://github.com/2gis/nuclear-river/blob/e1f5922c0df19be9c2a9ca08d521302c82223b67/Querying/Querying.Edm/Properties/AssemblyInfo.cs#L7)):*
Можно актуализировать

---

*[Querying/Tests/Querying.Edm.Tests/QueryExecution.Tests.v2.ncrunchproject, line 1 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/51#-KDTPXQAZCVjiHWIP3l4:-KDTPXQBSkgjhuaYGlD9:960046249) ([raw file](https://github.com/2gis/nuclear-river/blob/e1f5922c0df19be9c2a9ca08d521302c82223b67/Querying/Tests/Querying.Edm.Tests/QueryExecution.Tests.v2.ncrunchproject#L1)):*
Давай потом отдельно удалим все .ncrunchproject?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/51)*

**Comment by rechkalov** [comment]
Reviewed 231 of 266 files at r1, 1 of 1 files at r2, 32 of 32 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/51)*

**Comment by denisivan0v** [comment]
Review status: 164 of 193 files reviewed at latest revision, 4 unresolved discussions.

---

*[CustomerIntelligence/CustomerIntelligence.Querying.Host/Properties/AssemblyInfo.cs, line 7 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/51#-KDTGgLT6Hq7rqyOtyvq:-KDY9QBryCeiZaC07PBx:-499146009) ([raw file](https://github.com/2gis/nuclear-river/blob/e1f5922c0df19be9c2a9ca08d521302c82223b67/CustomerIntelligence/CustomerIntelligence.Querying.Host/Properties/AssemblyInfo.cs#L7)):*
Done.

---

*[CustomerIntelligence/CustomerIntelligence.Querying.Host/QueryBuilder/Content/odata-query-builder.css, line 1 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/51#-KDTGxpwtECCYz16PpLz:-KDY9V_MPgmmqr8gYje9:-1321813576) ([raw file](https://github.com/2gis/nuclear-river/blob/e1f5922c0df19be9c2a9ca08d521302c82223b67/CustomerIntelligence/CustomerIntelligence.Querying.Host/QueryBuilder/Content/odata-query-builder.css#L1)):*
Спорный вопрос. Он в CI-то не особо нужен, а впаривать его всем, кто будет пакет пользовать вроде не хорошо.
К тому же, какая-то там история есть с контентом в nupkg. +@maximpashuk подскажет

---

*[Querying/Querying.Edm/Properties/AssemblyInfo.cs, line 7 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/51#-KDTMt_m98cLqrQlYI89:-KDY9RMUqpDF4KTg20ka:-499146009) ([raw file](https://github.com/2gis/nuclear-river/blob/e1f5922c0df19be9c2a9ca08d521302c82223b67/Querying/Querying.Edm/Properties/AssemblyInfo.cs#L7)):*
Done.

---

*[Querying/Tests/Querying.Edm.Tests/QueryExecution.Tests.v2.ncrunchproject, line 1 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/51#-KDTPXQAZCVjiHWIP3l4:-KDY9RkG6ZGW_O3whmdz:-499146009) ([raw file](https://github.com/2gis/nuclear-river/blob/e1f5922c0df19be9c2a9ca08d521302c82223b67/Querying/Tests/Querying.Edm.Tests/QueryExecution.Tests.v2.ncrunchproject#L1)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/51)*

**Comment by rechkalov** [comment]
Reviewed 7 of 266 files at r1, 1 of 32 files at r3, 29 of 29 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/51)*

**Comment by maximpashuk** [comment]
Reviewed 221 of 266 files at r1, 1 of 1 files at r2, 30 of 32 files at r3, 3 of 3 files at r4, 29 of 29 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Querying/Querying.Edm/Emit/EmitClrTypeResolver.cs, line 17 \[r5\]](https://reviewable.io:443/reviews/2gis/nuclear-river/51#-KDb6Vsc1lgqYTmeii0l:-KDb6Vsc1lgqYTmeii0m:-2140716758) ([raw file](https://github.com/2gis/nuclear-river/blob/8c970272651ec0453fff69a703b44a647772b705/Querying/Querying.Edm/Emit/EmitClrTypeResolver.cs#L17)):*
Раз уж рефакторим, предлагаю динамическую assembly не называть CustomCode.
В динамических контроллерах там есть пример, assembly называется как "ИмяКонтекста"+Controllers. Думаю тут лучше также сделать.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/51)*

**Comment by denisivan0v** [comment]
Review status: 190 of 191 files reviewed at latest revision, 1 unresolved discussion.

---

*[Querying/Querying.Edm/Emit/EmitClrTypeResolver.cs, line 17 \[r5\]](https://reviewable.io:443/reviews/2gis/nuclear-river/51#-KDb6Vsc1lgqYTmeii0l:-KDbP1uAGM33L3RCSSBd:-499146009) ([raw file](https://github.com/2gis/nuclear-river/blob/8c970272651ec0453fff69a703b44a647772b705/Querying/Querying.Edm/Emit/EmitClrTypeResolver.cs#L17)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/51)*

**Comment by maximpashuk** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/51)*

**Pull request merged**
