### PR TITLE
Сделал StateInitialization Более управляемым

### PR DESCRIPTION
**Pull request by rechkalov**
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/137)

### CODE REVIEW

**Comment by denisivan0v** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[Replication/Replication.OperationsProcessing/Primary/EmptyOperationRegistry.cs, line 6 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/137#-KXeR-_dpAKg20lvpffA:-KXeR-_dpAKg20lvpffB:b-jrtt3d) ([raw file](https://github.com/2gis/nuclear-river/blob/251c4ef63c657236011de5cf50276fb9839b6066/Replication/Replication.OperationsProcessing/Primary/EmptyOperationRegistry.cs#L6)):*
> EmptyOperationRegistry
`NullOperationRegistry`aka null pattern

---

*[StateInitialization/StateInitialization.Core/Actors/BulkReplicationActor.cs, line 53 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/137#-KXeRGO4j0kLwkLvImjT:-KXeRGO4j0kLwkLvImjU:bx66gv5) ([raw file](https://github.com/2gis/nuclear-river/blob/251c4ef63c657236011de5cf50276fb9839b6066/StateInitialization/StateInitialization.Core/Actors/BulkReplicationActor.cs#L53)):*
> CurrentLogger.Instance = command.Logger
Нужен нормальный DI

---

*[StateInitialization/StateInitialization.Core/Actors/BulkReplicationActor.cs, line 281 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/137#-KXeRYmTG1oxh_Yx7vKw:-KXeRYmTG1oxh_Yx7vKx:be97pm5) ([raw file](https://github.com/2gis/nuclear-river/blob/251c4ef63c657236011de5cf50276fb9839b6066/StateInitialization/StateInitialization.Core/Actors/BulkReplicationActor.cs#L281)):*
> CurrentLogger.Instance
Нужен нормальный DI

---

*[StateInitialization/StateInitialization.Core/Actors/SequentialPipelineActor.cs, line 35 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/137#-KXeR_Q4OQLasjJ7YIBU:-KXeR_Q4OQLasjJ7YIBV:be97pm5) ([raw file](https://github.com/2gis/nuclear-river/blob/251c4ef63c657236011de5cf50276fb9839b6066/StateInitialization/StateInitialization.Core/Actors/SequentialPipelineActor.cs#L35)):*
> CurrentLogger.Instance
Нужен нормальный DI

---

*[StateInitialization/StateInitialization.Core/Commands/ReplicateInBulkCommand.cs, line 29 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/137#-KXeRnXmiO6NeKqPqpQC:-KXeRnXmiO6NeKqPqpQD:b-w8byu1) ([raw file](https://github.com/2gis/nuclear-river/blob/251c4ef63c657236011de5cf50276fb9839b6066/StateInitialization/StateInitialization.Core/Commands/ReplicateInBulkCommand.cs#L29)):*
> ILogger logger = null
Не стоит передавать экземпляр логера в команде. Тут только параметры выполнения.

---

*[StateInitialization/StateInitialization.Core/Logging/ILogger.cs, line 8 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/137#-KXeSCQacaHP1hxlazdT:-KXeSCQacaHP1hxlazdU:b-nmixts) ([raw file](https://github.com/2gis/nuclear-river/blob/251c4ef63c657236011de5cf50276fb9839b6066/StateInitialization/StateInitialization.Core/Logging/ILogger.cs#L8)):*
> ILogger
Думаю, стоит использовать существующую абстракцию `ITracer`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/137)*

**Comment by rechkalov** [comment]
Review status: 13 of 15 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[StateInitialization/StateInitialization.Core/Actors/BulkReplicationActor.cs, line 53 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/137#-KXeRGO4j0kLwkLvImjT:-KYDkeWbwPis7ndIHsXx:bekq9ha) ([raw file](https://github.com/2gis/nuclear-river/blob/251c4ef63c657236011de5cf50276fb9839b6066/StateInitialization/StateInitialization.Core/Actors/BulkReplicationActor.cs#L53)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary><blockquote>

> CurrentLogger.Instance = command.Logger
Нужен нормальный DI
</blockquote></details>

Смотри ниже

---

*[StateInitialization/StateInitialization.Core/Actors/BulkReplicationActor.cs, line 281 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/137#-KXeRYmTG1oxh_Yx7vKw:-KYDkhmZBFJO4PFZ16QP:bekq9ha) ([raw file](https://github.com/2gis/nuclear-river/blob/251c4ef63c657236011de5cf50276fb9839b6066/StateInitialization/StateInitialization.Core/Actors/BulkReplicationActor.cs#L281)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary><blockquote>

> CurrentLogger.Instance
Нужен нормальный DI
</blockquote></details>

Смотри ниже

---

*[StateInitialization/StateInitialization.Core/Actors/SequentialPipelineActor.cs, line 35 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/137#-KXeR_Q4OQLasjJ7YIBU:-KYDkl-fmAPcjDZv_l0Z:bekq9ha) ([raw file](https://github.com/2gis/nuclear-river/blob/251c4ef63c657236011de5cf50276fb9839b6066/StateInitialization/StateInitialization.Core/Actors/SequentialPipelineActor.cs#L35)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary><blockquote>

> CurrentLogger.Instance
Нужен нормальный DI
</blockquote></details>

Смотри ниже

---

*[StateInitialization/StateInitialization.Core/Commands/ReplicateInBulkCommand.cs, line 29 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/137#-KXeRnXmiO6NeKqPqpQC:-KYDkllY5EucIxcD9EYF:bekq9ha) ([raw file](https://github.com/2gis/nuclear-river/blob/251c4ef63c657236011de5cf50276fb9839b6066/StateInitialization/StateInitialization.Core/Commands/ReplicateInBulkCommand.cs#L29)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary><blockquote>

> ILogger logger = null
Не стоит передавать экземпляр логера в команде. Тут только параметры выполнения.
</blockquote></details>

Смотри ниже

---

*[StateInitialization/StateInitialization.Core/Logging/ILogger.cs, line 8 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/137#-KXeSCQacaHP1hxlazdT:-KYDipbdYKvvcyE_k0sB:b-tngzt9) ([raw file](https://github.com/2gis/nuclear-river/blob/251c4ef63c657236011de5cf50276fb9839b6066/StateInitialization/StateInitialization.Core/Logging/ILogger.cs#L8)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary><blockquote>

> ILogger
Думаю, стоит использовать существующую абстракцию `ITracer`
</blockquote></details>

Ты хорошо представляешь количество новых зависимостей, объём изменений и их стоимость? Готов на затраты? Думал о нормальном DI, когда писал Console.WriteLine?

---

*[Replication/Replication.OperationsProcessing/Primary/EmptyOperationRegistry.cs, line 6 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/137#-KXeR-_dpAKg20lvpffA:-KYDiiQ7ZNGdVyiL5l0n:b-bnue53) ([raw file](https://github.com/2gis/nuclear-river/blob/251c4ef63c657236011de5cf50276fb9839b6066/Replication/Replication.OperationsProcessing/Primary/EmptyOperationRegistry.cs#L6)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary><blockquote>

> EmptyOperationRegistry
`NullOperationRegistry`aka null pattern
</blockquote></details>

Не проблема.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/137)*

**Comment by denisivan0v** [comment]
Review status: 13 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[StateInitialization/StateInitialization.Core/Logging/ILogger.cs, line 8 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/137#-KXeSCQacaHP1hxlazdT:-KYH4Ovb-dxvSxppdKOH:b9nr4gk) ([raw file](https://github.com/2gis/nuclear-river/blob/251c4ef63c657236011de5cf50276fb9839b6066/StateInitialization/StateInitialization.Core/Logging/ILogger.cs#L8)):*
<details><summary><i>Previously, rechkalov (a.rechkalov) wrote…</i></summary><blockquote>

Ты хорошо представляешь количество новых зависимостей, объём изменений и их стоимость? Готов на затраты? Думал о нормальном DI, когда писал Console.WriteLine?
</blockquote></details>

Да - на все вопросы. Затраты стоит оценить по сравнению с профитом.
Наличие Console.WriteLine предполагает безусловное логирование в stdout. У меня не было потребностей менять это поведение. 
На самом деле, есть еще как минимум два варианта решения. Первый - ключ, управляющий полнотой логирования. Второй - перенаправление вывода. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/137)*

**Comment by rechkalov** [comment]
Review status: 5 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[StateInitialization/StateInitialization.Core/Logging/ILogger.cs, line 8 at r1](https://reviewable.io:443/reviews/2gis/nuclear-river/137#-KXeSCQacaHP1hxlazdT:-KYRasqz6pQgmnhQ1Y1P:b-vut8rz) ([raw file](https://github.com/2gis/nuclear-river/blob/251c4ef63c657236011de5cf50276fb9839b6066/StateInitialization/StateInitialization.Core/Logging/ILogger.cs#L8)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary><blockquote>

Да - на все вопросы. Затраты стоит оценить по сравнению с профитом.
Наличие Console.WriteLine предполагает безусловное логирование в stdout. У меня не было потребностей менять это поведение. 
На самом деле, есть еще как минимум два варианта решения. Первый - ключ, управляющий полнотой логирования. Второй - перенаправление вывода. 
</blockquote></details>

Ок, откатил. Когда будет свободное время оценим и сделаем иначе.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/137)*

**Comment by denisivan0v** [comment]
Reviewed 9 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/137)*

**Comment by denisivan0v** [comment]
@rechkalov, актуализируй бранч feature/options, есть конфликты

**Comment by denisivan0v** [comment]
Reviewed 4 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/137)*

**Comment by denisivan0v** [comment]
Актуализируй бранч плз

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/137#-:-KbAelp6-k9ujh2nxz3r:bhvyoou)*

**Pull request merged**
