### PR TITLE
import forecasts feature

### PR DESCRIPTION
**Pull request by rechkalov**
[Review on Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/41)

### CODE REVIEW

**Comment by rechkalov** [comment]
ping @denisivan0v @maximpashuk

**Comment by maximpashuk** [comment]
Reviewed 53 of 53 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitAccumulator.cs, line 27 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KBwJmO3jle-2ir_1H9Y:-KBwJmO3jle-2ir_1H9Z:-1475370732) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitAccumulator.cs#L27)):*
C# 6.0 на дворе, давай по-модному
{
  ["firmpopularity"] = new FirmPopularityCorporateBusMessageParser(),
  ["rubricpopularity"] = RubricPopularityCorporateBusMessageParser()
}

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/41)*

**Comment by rechkalov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitAccumulator.cs, line 27 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KBwJmO3jle-2ir_1H9Y:-KBzcxqcpw9q9mPHOny9:-132916406) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitAccumulator.cs#L27)):*
В целом я не против, но есть одно замечание: синтаксис с фигурными скобками использует метод Add, а новомодный - индексатор. Поэтому есть отличие в поведении: старый синтаксис защищает от того, чтобы по тупняку добавить два одинаковых ключа, а новомодный - нет, он заменит ранее добавленное значение ключа.

Если ты отметёшь это замечание как незначащее, то можно использовать новый синтаксис.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/41)*

**Comment by denisivan0v** [comment]
Reviewed 53 of 53 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[Common.Metadata/Identities/ImportStatisticsMetadataIdentity.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCTuGGXpoNqbwFWz9vR:-KCTuGGXpoNqbwFWz9vS:1145320099) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/Common.Metadata/Identities/ImportStatisticsMetadataIdentity.cs#L11)):*
Нужен закрывающий слэш?

---

*[CustomerIntelligence/CustomerIntelligence.Domain/Specifications/Specs.Map.Facts.Statistics.cs, line 88 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCTwlevzJl6nQ9WRBFh:-KCTwlevzJl6nQ9WRBFi:-315030025) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/CustomerIntelligence/CustomerIntelligence.Domain/Specifications/Specs.Map.Facts.Statistics.cs#L88)):*
Можно остаться только на query-синтаксисе

```csharp
from firm in q.For<Facts::Firm>()
join project in q.For<Facts::Project>() on firm.OrganizationUnitId equals project.OrganizationUnitId
join forecast in q.For<Bit::FirmForecast>() on firm.Id equals forecast.FirmId into forecasts
from forecast in forecasts.DefaultIfEmpty()
select new Statistics::FirmForecast
{
     ProjectId = project.Id,
     FirmId = firm.Id,
     ForecastClick = forecast == null ? null : (int?)forecast.ForecastClick,
     ForecastAmount = forecast == null ? null : (decimal?)forecast.ForecastAmount
}
```

---

*[CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitAccumulator.cs, line 27 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KBwJmO3jle-2ir_1H9Y:-KCTtBnCAJxbdwRSxoTE:1592840018) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitAccumulator.cs#L27)):*
Я - ретроград, я за старый синтаксис

---

*[CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitHandler.cs, line 50 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCTxh190ki07Th2YWJ0:-KCTxh1A5ZENkve5oAwj:445914677) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitHandler.cs#L50)):*
Для одного типа DTO есть несколько importer-ов? Это странно..

---

*[Replication/Replication.Core.API/Facts/IStatisticsImporterFactory.cs, line 8 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCTynIXE0WB3JcndRmM:-KCTynIXE0WB3JcndRmN:20912750) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/Replication/Replication.Core.API/Facts/IStatisticsImporterFactory.cs#L8)):*
Тот же вопрос по тип DTO и обработчики

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/41)*

**Comment by rechkalov** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[Common.Metadata/Identities/ImportStatisticsMetadataIdentity.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCTuGGXpoNqbwFWz9vR:-KCU7Ni9xYOLubDQO8JZ:-288387736) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/Common.Metadata/Identities/ImportStatisticsMetadataIdentity.cs#L11)):*
Даже обязателен - это связано с нюансами объединения Uri:

```
new Uri(new Uri("erm://metadata/foo1"), new Uri("foobar", UriKind.Relative));
new Uri(new Uri("erm://metadata/foo1/"), new Uri("foobar", UriKind.Relative));
```

Я сильно глубоко не копал, но в первом случае `foobar` вытеснит `foo1`, получится такое: `erm://metadata/foobar`
Во втором `erm://metadata/foo1/foobar`

Поскольку этот id используется как база для построения конкретных - то логично завершать его слешом.

Кто-то запинал костыль - метод WithRelative, и ему без разницы, если слеш или нет, но это не полное решение: есть ещё и полезный метод Uri.IsBaseOf, для него тоже слеш важен, например, без него uri `erm://metadata/foo/bar` является базовым для `erm://metadata/foo/abc`

Но WithRelative считает себя слишком умным и слеш на конце молча убирает. 

Поэтому да, он нужен тут и в `UnityStatisticsImporterFactory`

---

*[CustomerIntelligence/CustomerIntelligence.Domain/Specifications/Specs.Map.Facts.Statistics.cs, line 88 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCTwlevzJl6nQ9WRBFh:-KCUC4YI_IN9_KDVSDh1:-414003928) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/CustomerIntelligence/CustomerIntelligence.Domain/Specifications/Specs.Map.Facts.Statistics.cs#L88)):*
Может быть, хотя я не уверен в том, что будет построен корректный запрос. 
В любом случае, мы договорились сделать поля не Nullable, а сам объект FirmForecast опциональным - это значительно упростит этот запрос.

---

*[CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitAccumulator.cs, line 27 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KBwJmO3jle-2ir_1H9Y:-KCUCnyFXfkoA8x07JMa:1261201653) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitAccumulator.cs#L27)):*
Тут фишка не только в синтаксисе, но и в поведении.

---

*[CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitHandler.cs, line 50 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCTxh190ki07Th2YWJ0:-KCUD2NZPTnBD42wYhsl:1951363573) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitHandler.cs#L50)):*
Да, так получается. Один importer работает только с одной целевой сущностью, а если в dto мастер-система объединила несколько?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/41)*

**Comment by denisivan0v** [comment]
Reviewed 4 of 5 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[Common.Metadata/Identities/ImportStatisticsMetadataIdentity.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCTuGGXpoNqbwFWz9vR:-KCUZD2H0J7pBDzdQDrA:-1926231486) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/Common.Metadata/Identities/ImportStatisticsMetadataIdentity.cs#L11)):*
Лучше бы не работать с Uri напрямую, т.к. детали реализации ключей метаданных библиотеки metamodelling. Было бы замечательно всю эту логику скрыть в metamodelling

---

*[CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitHandler.cs, line 50 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCTxh190ki07Th2YWJ0:-KCU_HqeDhYLx8bpP47N:118537958) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitHandler.cs#L50)):*
Ну это же все равно один тип DTO? Он может иметь свойства или колекции каких-то типов, но все они - в рамках одного типа DTO. Так же?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/41)*

**Comment by rechkalov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Common.Metadata/Identities/ImportStatisticsMetadataIdentity.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCTuGGXpoNqbwFWz9vR:-KCUaGAWWq4rTHF4KOye:-1878686641) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/Common.Metadata/Identities/ImportStatisticsMetadataIdentity.cs#L11)):*
Может быть. Но сейчас работа с Uri - общепринятая. А перепиливать metamodeling - это далеко а рамками этой задачи.

---

*[CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitHandler.cs, line 50 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCTxh190ki07Th2YWJ0:-KCUaUr3OlfqXfmfdPOP:-1248887687) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitHandler.cs#L50)):*
Да, это один тип и инстанс dto.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/41)*

**Comment by denisivan0v** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Common.Metadata/Identities/ImportStatisticsMetadataIdentity.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCTuGGXpoNqbwFWz9vR:-KCUbdQZev1k0mndj1x8:686810442) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/Common.Metadata/Identities/ImportStatisticsMetadataIdentity.cs#L11)):*
Заведи плиз хотя бы issue на этот счет

---

*[CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitHandler.cs, line 50 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCTxh190ki07Th2YWJ0:-KCUbvi1f0PYmdV_5J7m:775671283) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitHandler.cs#L50)):*
Не понимаю тогда..

```csharp
foreach (var importer in _statisticsImporterFactory.Create(dto.GetType())){ ... }
```

Тут мы получаем несколько importer-ов для одного типа DTO

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/41)*

**Comment by rechkalov** [comment]
Review status: 43 of 63 files reviewed at latest revision, 4 unresolved discussions.

---

*[Common.Metadata/Identities/ImportStatisticsMetadataIdentity.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCTuGGXpoNqbwFWz9vR:-KCVAObvuxZ2JnCbXiRd:-114992504) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/Common.Metadata/Identities/ImportStatisticsMetadataIdentity.cs#L11)):*
Усложнение обработчиков решило этот вопрос.

---

*[CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitHandler.cs, line 50 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCTxh190ki07Th2YWJ0:-KCVAUbTo1q0IJqhe-Pp:-936490460) ([raw file](https://github.com/2gis/nuclear-river/blob/0eb8b18730cb09f5d74c6dae7f92799ebaea544f/CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitHandler.cs#L50)):*
Устно договорились на усложнение обработчика так, чтобы он включал все необходимые цели для одной dto

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/41)*

**Comment by denisivan0v** [comment]
Reviewed 21 of 23 files at r3.
Review status: 61 of 63 files reviewed at latest revision, 6 unresolved discussions.

---

*[Common.Metadata/Builders/ImportStatisticsMetadataBuilder.cs, line 18 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCVJ7AKJ_sW0m6DEXVJ:-KCVJ7AKJ_sW0m6DEXVK:109174990) ([raw file](https://github.com/2gis/nuclear-river/blob/27fa302129b9f6febbbe5eec2c88206dc9e3d9d9/Common.Metadata/Builders/ImportStatisticsMetadataBuilder.cs#L18)):*
Let's make descriptions in English in classes from River's platform 

---

*[Common.Metadata/Builders/ImportStatisticsMetadataBuilder.cs, line 24 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCVJTrFGl1j6woPdry6:-KCVJTrFGl1j6woPdry7:2102891203) ([raw file](https://github.com/2gis/nuclear-river/blob/27fa302129b9f6febbbe5eec2c88206dc9e3d9d9/Common.Metadata/Builders/ImportStatisticsMetadataBuilder.cs#L24)):*
Именование - ImportToFact**s**

---

*[Replication/Replication.Core.API/Facts/IImportDocumentMetadataProcessor.cs, line 9 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCVKYLsHSOqTfULqHDu:-KCVKYLtgB0AL7w-8whE:1862669814) ([raw file](https://github.com/2gis/nuclear-river/blob/27fa302129b9f6febbbe5eec2c88206dc9e3d9d9/Replication/Replication.Core.API/Facts/IImportDocumentMetadataProcessor.cs#L9)):*
Наверное стоит и название метода переименовать

---

*[Replication/Replication.Core/Facts/IImportDocumentFeatureProcessor.cs, line 3 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCVKjo3-VvYfeSor2A5:-KCVKjo3-VvYfeSor2A6:-1592092260) ([raw file](https://github.com/2gis/nuclear-river/blob/27fa302129b9f6febbbe5eec2c88206dc9e3d9d9/Replication/Replication.Core/Facts/IImportDocumentFeatureProcessor.cs#L3)):*
Можем не использовать понятия из metamodelling-а (metadata, feature, etc)? `IDocumentImporter`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/41)*

**Comment by denisivan0v** [comment]
Reviewed 2 of 23 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/41)*

**Comment by rechkalov** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[Replication/Replication.Core.API/Facts/IImportDocumentMetadataProcessor.cs, line 9 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCVKYLsHSOqTfULqHDu:-KCVf1wtYI_SM04cdZTe:105756720) ([raw file](https://github.com/2gis/nuclear-river/blob/27fa302129b9f6febbbe5eec2c88206dc9e3d9d9/Replication/Replication.Core.API/Facts/IImportDocumentMetadataProcessor.cs#L9)):*
Пока оно достаточно органично вписывается. Можно для сравнения посмотреть IStatisticsProcessor, IAggregateProcessor, итп.

---

*[Replication/Replication.Core/Facts/IImportDocumentFeatureProcessor.cs, line 3 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/41#-KCVKjo3-VvYfeSor2A5:-KCVdfPuE0Lu-JVw4MsH:-503361092) ([raw file](https://github.com/2gis/nuclear-river/blob/27fa302129b9f6febbbe5eec2c88206dc9e3d9d9/Replication/Replication.Core/Facts/IImportDocumentFeatureProcessor.cs#L3)):*
Тут это нарочно. В metamodeling есть feature, а это featureProcessor, чьё поведение управляется фичей.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/41)*

**Pull request merged**
