### PR TITLE
Updates in documentation platform (gitbook)

### PR DESCRIPTION
**Pull request by denisivan0v**
@maximpashuk @rechkalov

---
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/79)

### CODE REVIEW

**Comment by maximpashuk** [comment]
Reviewed 42 of 42 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package.json, line 29 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/79#-KHYZKZWok0M04KkCzaX:-KHYZKZWok0M04KkCzaY:501447906) ([raw file](https://github.com/2gis/nuclear-river/blob/3c5b487685d8dd2afd8f2c9c0621c2913d78b90c/package.json#L29)):*
> ```JSON
>       "name": "Maxim Pashuk",
>       "email": "m.pashuk@2gis.ru"
>     }
> ```

Сергея надо добавить

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/79)*

**Comment by denisivan0v** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package.json, line 29 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/79#-KHYZKZWok0M04KkCzaX:-KHY_a6CsXU9zR_8sPp-:737356527) ([raw file](https://github.com/2gis/nuclear-river/blob/3c5b487685d8dd2afd8f2c9c0621c2913d78b90c/package.json#L29)):*
<details><summary><i>Previously, maximpashuk (Maxim Pashuk) wrote…</i></summary>
> Сергея надо добавить</details>
Это вроде как список контрибьюторов в документацию

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/79)*

**Comment by rechkalov** [comment]
Reviewed 42 of 42 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/79)*

**Comment by maximpashuk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package.json, line 29 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/79#-KHYZKZWok0M04KkCzaX:-KHYxgiGNkFbttha2BOm:-197006833) ([raw file](https://github.com/2gis/nuclear-river/blob/3c5b487685d8dd2afd8f2c9c0621c2913d78b90c/package.json#L29)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Это вроде как список контрибьюторов в документацию</details>
Тогда норм

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/79)*

**Pull request merged**
