### PR TITLE
Added possibility to set data changes handler in EntityActorBase

### PR DESCRIPTION
**Pull request by unsanny**
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/93)

### CODE REVIEW

**Comment by rechkalov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Replication/Replication.Core/Actors/EntityActorBase.cs, line 58 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/93#-KJEvyVt_buzfsdMlrJI:-KJEvyVuNxH1BEmAzrja:460188660) ([raw file](https://github.com/2gis/nuclear-river/blob/a21d05191a7dcc6e41c92c3808b166d090e10210/Replication/Replication.Core/Actors/EntityActorBase.cs#L58)):*
> ```Smalltalk
>             events.AddRange(actor.ExecuteCommands(commands));
> 
>             actor = new DeleteDataObjectsActor<TDataObject>(_query, _bulkRepository, _equalityComparerFactory, _storageBasedDataObjectAccessor, _dataChangesHandler);
> ```

Кажется, конструкторы CreateDataObjectsActor/SyncDataObjectsActor/DeleteDataObjectsActor с четырьмя параметрами больше не нужен, может их удалить?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/93)*

**Comment by denisivan0v** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Replication/Replication.Core/Actors/EntityActorBase.cs, line 58 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/93#-KJEvyVt_buzfsdMlrJI:-KJF3lP_CC4NsbBWYi6w:1063375596) ([raw file](https://github.com/2gis/nuclear-river/blob/a21d05191a7dcc6e41c92c3808b166d090e10210/Replication/Replication.Core/Actors/EntityActorBase.cs#L58)):*
<details><summary><i>Previously, rechkalov (a.rechkalov) wrote…</i></summary>
> Кажется, конструкторы CreateDataObjectsActor/SyncDataObjectsActor/DeleteDataObjectsActor с четырьмя параметрами больше не нужен, может их удалить?
</details>
Соглашусь

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/93)*

**Comment by unsanny** [comment]
готово

**Comment by denisivan0v** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/93)*

**Comment by rechkalov** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/93)*

**Pull request merged**
