### PR TITLE
Feature/category123

### PR DESCRIPTION
**Pull request by maximpashuk**
Обновлённый pull request, актуализированный от master.

[Review on Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/5)

### CODE REVIEW

**Comment by denisivan0v** [comment]
Reviewed 63 of 63 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CustomerIntelligence/Schemas/CustomerIntelligence.sql, line 15 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/5#-K83awxKx8iEFICOWIqY:-K83awxKx8iEFICOWIqZ:-55505105) ([raw file](https://github.com/2gis/nuclear-river/blob/8f34acccdd8fd894f7396ddf7e1c1ec46c6f9e7c/CustomerIntelligence/Schemas/CustomerIntelligence.sql#L15)):*
non unicode symbols?n

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/5)*

**Comment by maximpashuk** [comment]
*[CustomerIntelligence/Schemas/CustomerIntelligence.sql, line 15 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/5#-K83awxKx8iEFICOWIqY:-K83g9sUrZnDiyuw_hNr:1690513697) ([raw file](https://github.com/2gis/nuclear-river/blob/8f34acccdd8fd894f7396ddf7e1c1ec46c6f9e7c/CustomerIntelligence/Schemas/CustomerIntelligence.sql#L15)):*
saved as utf8

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/5)*

**Comment by denisivan0v** [comment]
Reviewed 1 of 4 files at r2.
Review status: 59 of 62 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/5)*

**Comment by denisivan0v** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/5)*

**Pull request merged**
