### PR TITLE
Renames facts\aggregates schemas

### PR DESCRIPTION
**Pull request by rechkalov**
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/127)

### CODE REVIEW

**Comment by denisivan0v** [comment]
Reviewed 10 of 12 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[CustomerIntelligence/Tests/CustomerIntelligence.Querying.Tests/MetadataTests.cs, line 89 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/127#-KOPKBfVrL7jPJMp8VN7:-KOPKBfVrL7jPJMp8VN8:b-y8sxz7) ([raw file](https://github.com/2gis/nuclear-river/blob/e43e5456dc7d9246ada84aefb235197de0f34b7c/CustomerIntelligence/Tests/CustomerIntelligence.Querying.Tests/MetadataTests.cs#L89)):*
> ```Smalltalk
>         [TestCase("CustomerIntelligence/ConceptualModel/Territory")]
>         [TestCase("CustomerIntelligence/StoreModel")]
>         [TestCase("CustomerIntelligence/StoreModel/Aggregates.CategoryGroup")]
> ```

Нужно ли это изменение согласовать с CRM-командой? В том смысле, что повлияет ли это на API?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/127)*

**Comment by denisivan0v** [comment]
Reviewed 2 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/127)*

**Comment by maximpashuk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CustomerIntelligence/Tests/CustomerIntelligence.Querying.Tests/MetadataTests.cs, line 89 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/127#-KOPKBfVrL7jPJMp8VN7:-KOiLLAbftWIaC6ecCto:bi26i5q) ([raw file](https://github.com/2gis/nuclear-river/blob/e43e5456dc7d9246ada84aefb235197de0f34b7c/CustomerIntelligence/Tests/CustomerIntelligence.Querying.Tests/MetadataTests.cs#L89)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Нужно ли это изменение согласовать с CRM-командой? В том смысле, что повлияет ли это на API?
</details>
Думаю, что нет.

Изменения хоть и в Querying, но в части StoreModel.
StoreModel извне вообще не виден никак, так что CRM-команда ничего не почуствует.

Так что если возражений нет, то можно сливать.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/127)*

**Comment by denisivan0v** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CustomerIntelligence/Tests/CustomerIntelligence.Querying.Tests/MetadataTests.cs, line 89 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/127#-KOPKBfVrL7jPJMp8VN7:-KOiZL_2JDwsiRLB-WIc:bq7fvia) ([raw file](https://github.com/2gis/nuclear-river/blob/e43e5456dc7d9246ada84aefb235197de0f34b7c/CustomerIntelligence/Tests/CustomerIntelligence.Querying.Tests/MetadataTests.cs#L89)):*
<details><summary><i>Previously, maximpashuk (Maxim Pashuk) wrote…</i></summary>
> Думаю, что нет.
> 
> Изменения хоть и в Querying, но в части StoreModel.
> StoreModel извне вообще не виден никак, так что CRM-команда ничего не почуствует.
> 
> Так что если возражений нет, то можно сливать.
> 
</details>
тогда :lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/127)*

**Comment by maximpashuk** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/127)*

**Pull request merged**
