### PR TITLE
Заменил делегат на метод класса

### PR DESCRIPTION
**Pull request by rechkalov**
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/125)

### CODE REVIEW

**Comment by denisivan0v** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[StateInitialization/StateInitialization.Core/BulkReplicationActor.cs, line 211 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/125#-KOK2vo4DepvZ2XXPsVG:-KOK2vo4DepvZ2XXPsVH:710712446) ([raw file](https://github.com/2gis/nuclear-river/blob/5e94b1b78dc24278802e281d2d82097252a34526/StateInitialization/StateInitialization.Core/BulkReplicationActor.cs#L211)):*
> ```Smalltalk
>         }
> 
>         void Execute(IReadOnlyCollection<ICommand> commands, IReadOnlyCollection<IActor> actors)
> ```

private static...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/125)*

**Comment by denisivan0v** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[StateInitialization/StateInitialization.Core/BulkReplicationActor.cs, line 211 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/125#-KOK2vo4DepvZ2XXPsVG:-KOK317VRX1Jcp-EhaGe:-2129561006) ([raw file](https://github.com/2gis/nuclear-river/blob/5e94b1b78dc24278802e281d2d82097252a34526/StateInitialization/StateInitialization.Core/BulkReplicationActor.cs#L211)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> private static...
</details>
Но и какая разница?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/125)*

**Comment by denisivan0v** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/125)*

**Comment by rechkalov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[StateInitialization/StateInitialization.Core/BulkReplicationActor.cs, line 211 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/125#-KOK2vo4DepvZ2XXPsVG:-KOK7iXlWszdCcsHMWhx:784707432) ([raw file](https://github.com/2gis/nuclear-river/blob/5e94b1b78dc24278802e281d2d82097252a34526/StateInitialization/StateInitialization.Core/BulkReplicationActor.cs#L211)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Но и какая разница?
</details>
Нет захвата локальной переменной, при вызове метода ReplaceInBulk не создаётся экземпляр делегата, проще читать (метод определён ниже использования), меньше отступов. 
В общем, ничего особенного, но глазу приятнее :)

PS. private - да, а static - нет, поскольку наш стиль требует помещать static методы перед не-static (обсудим изменение стиля? он явно противоречит рекомендациям из "Clean Code")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/125)*

**Comment by denisivan0v** [comment]
This RP is outdated due to changes made in #121 while codereview loop

**Pull request closed without merging**
