### PR TITLE
Extracting just NuClear River libraries

### PR DESCRIPTION
**Pull request by denisivan0v**
From this point https://github.com/2gis/nuclear-river repo will contain code just for libraries.
Customer Intelligence Read model built with these libraries moved to another repo https://github.com/2gis/nuclear-river-customer-intelligence

---
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/131)

### CODE REVIEW

**Comment by maximpashuk** [comment]
1. Оствлена папка tools.
В ней лежат тесты андрея по CustomerIntelligence - надо их перенести.

2. Оставлена папка docs.
Может быть это и ок, но в ней есть ru/customer-intelligence (описание агрегатов) - надо её перенести

---

Review status: 0 of 452 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/131#-:-KPD-WLLtExUic8R9Yxv:bmh8bpa)*

**Comment by maximpashuk** [comment]
Reviewed 452 of 452 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/131)*

**Comment by denisivan0v** [comment]
Папка docs - ок, документацию еще нужно актуализировать. Сделаем это в рамках отдельной задачи
Папку tools удалил

---

Review status: 452 of 454 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/131#-:-KPHbqum3hkZnifXTwcu:b-ifquvm)*

**Comment by maximpashuk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/131#-:-KPHguYgE9S9VdZcP4Kx:bnfp4nl)*

**Pull request merged**
