### PR TITLE
added binary serializer for service bus

### PR DESCRIPTION
**Pull request by pomadin**
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/119)

### CODE REVIEW

**Comment by denisivan0v** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Replication/Replication.OperationsProcessing/Transports/IBinaryEventSerializer.cs, line 5 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/119#-KNk6RSuzGUyqg_zDm7i:-KNk6RSvPA9vlG1OhM7l:1427778193) ([raw file](https://github.com/2gis/nuclear-river/blob/b5420d3ee986f865e7c4e30e173056af791e8306/Replication/Replication.OperationsProcessing/Transports/IBinaryEventSerializer.cs#L5)):*
> ```Smalltalk
> namespace NuClear.Replication.OperationsProcessing.Transports
> {
>     public interface IBinaryEventSerializer
> ```

Мне не особо понятна идея введения дополнительных абстракций `IBinaryWriter` и `IBinaryReader`. Для конвертера и транформера они явно лишние.
Может быть они полезны при реалиазации `IBinaryEventSerializer`? Есть пример такой реализации?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/119)*

**Comment by pomadin** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Replication/Replication.OperationsProcessing/Transports/IBinaryEventSerializer.cs, line 5 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/119#-KNk6RSuzGUyqg_zDm7i:-KQz2L4bi3cQCcBvST5o:bv6szqg) ([raw file](https://github.com/2gis/nuclear-river/blob/b5420d3ee986f865e7c4e30e173056af791e8306/Replication/Replication.OperationsProcessing/Transports/IBinaryEventSerializer.cs#L5)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Мне не особо понятна идея введения дополнительных абстракций `IBinaryWriter` и `IBinaryReader`. Для конвертера и транформера они явно лишние.
> Может быть они полезны при реалиазации `IBinaryEventSerializer`? Есть пример такой реализации?
</details>
Исправил, как договаривались. Сменил реализацию на работу с массивом байт.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/119)*

**Comment by denisivan0v** [comment]
Reviewed 4 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/119)*

**Comment by denisivan0v** [comment]
@rechkalov ты посмотрел же?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/119#-:-KR2VUjCUUjb2mm6dE1w:bupciiv)*

**Comment by rechkalov** [comment]
OK, что-то я подзабыл детали, но выглядит неплохо.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/119#-:-KR2oVJKPPV8zGJkKmdD:b-61mzt9)*

**Pull request merged**
