### PR TITLE
Work on commands

### PR DESCRIPTION
**Pull request by rechkalov**
Explicit command (de)serialization
Explicit command processing
Some statistics\aggregates unification.

Based on feature/identitifiable

@maximpashuk, @denisivan0v

---
This change is [Review on Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/47)

### CODE REVIEW

**Comment by maximpashuk** [comment]
Reviewed 53 of 97 files at r1, 128 of 132 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Common.Metadata/Model/Operations/AggregateOperation.cs, line 5 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/47#-KCtRxgNflt7OOdnm5hE:-KCtRxgONwnJKJDNjVWo:-2137925572) ([raw file](https://github.com/2gis/nuclear-river/blob/fa8dc1d12aedb09733ae5357a67abbf730a86542/Common.Metadata/Model/Operations/AggregateOperation.cs#L5)):*
Мы уже обсуждали, но может быть всё же лучше IEntityType вместо int entityTypeId?
Сериализация\десериализация IEntityType это отдельный вопрос, int же в угоду простоте сериализации стоит, так?

---

*[Replication/Replication.Core/Aggregates/IndirectlyDependentEntityFeatureProcessor.cs, line 14 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/47#-KCtWDj3akz_6gHPqfeG:-KCtWDj3akz_6gHPqfeH:-433212690) ([raw file](https://github.com/2gis/nuclear-river/blob/fa8dc1d12aedb09733ae5357a67abbf730a86542/Replication/Replication.Core/Aggregates/IndirectlyDependentEntityFeatureProcessor.cs#L14)):*
Комментарий такой же как и для прямой зависимости

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/47)*

**Comment by rechkalov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Common.Metadata/Model/Operations/AggregateOperation.cs, line 5 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/47#-KCtRxgNflt7OOdnm5hE:-KCuD_Uo0R_IJNsaR_s8:-1466539005) ([raw file](https://github.com/2gis/nuclear-river/blob/fa8dc1d12aedb09733ae5357a67abbf730a86542/Common.Metadata/Model/Operations/AggregateOperation.cs#L5)):*
На самом деле я бы ещё сказал, что это не только упрощение, но и концентрация логики в одном месте. Сериализатору не нужно знать про всякие там реестры. Написано 146, значит 146. А вот уже обработчик команды может посмотреть в параметры команды и придраться: "А заказа №32 не существует", "А агрегат 146 не определён".

---

*[Replication/Replication.Core/Aggregates/IndirectlyDependentEntityFeatureProcessor.cs, line 14 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/47#-KCtWDj3akz_6gHPqfeG:-KCuNoCzV-EdGIv49qUQ:1214399572) ([raw file](https://github.com/2gis/nuclear-river/blob/fa8dc1d12aedb09733ae5357a67abbf730a86542/Replication/Replication.Core/Aggregates/IndirectlyDependentEntityFeatureProcessor.cs#L14)):*
Исправил

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/47)*

**Comment by maximpashuk** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/47)*

**Comment by maximpashuk** [comment]
Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/47)*

**Pull request merged**
