### PR TITLE
Changed IIdentifiable to have custom key

### PR DESCRIPTION
**Pull request by rechkalov**
ping @maximpashuk @denisivan0v

[Review on Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/38)

### CODE REVIEW

**Comment by denisivan0v** [comment]
Reviewed 5 of 38 files at r1.
Review status: 5 of 38 files reviewed at latest revision, 7 unresolved discussions.

---

*[Common.Metadata/Model/IAggregateEntity.cs, line 3 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBIJbIPAXX0J0KLFaFe:-KBIJbIPAXX0J0KLFaFf:-2054053501) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/Common.Metadata/Model/IAggregateEntity.cs#L3)):*
AggregateRoot?

---

*[Common.Metadata/Model/IdentityExtensions.cs, line 14 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBII_2GtgpqdCeoHlwZ:-KBII_2GtgpqdCeoHlw_:210119479) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/Common.Metadata/Model/IdentityExtensions.cs#L14)):*
`Create` is not a provider responsibility. Do we need a factory abstraction?

---

*[Common.Metadata/Model/IdentityExtensions.cs, line 14 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBIJDqkacT6HTCKJUgK:-KBIJDqkacT6HTCKJUgL:1045875480) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/Common.Metadata/Model/IdentityExtensions.cs#L14)):*
T -> TIdentifiable everywhere (or nowhere)

---

*[Common.Metadata/Model/IdentityExtensions.cs, line 26 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBIJ3wxmQAlcvpZBJSp:-KBIJ3wxmQAlcvpZBJSq:285119867) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/Common.Metadata/Model/IdentityExtensions.cs#L26)):*
Let's add this method to contact if we need it

---

*[Common.Metadata/Model/IdentityProviderBase.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBIFAlh2pOV1CBg8mL4:-KBIFAlh2pOV1CBg8mL5:-1652268188) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/Common.Metadata/Model/IdentityProviderBase.cs#L11)):*
Not sure we need singleton ever

---

*[Common.Metadata/Model/IIdentityProvider.cs, line 7 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBIDFEGSvyGqXMZs3sd:-KBIDFEGSvyGqXMZs3se:1861789240) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/Common.Metadata/Model/IIdentityProvider.cs#L7)):*
unicode

---

*[Common.Metadata/Model/IIdentityProvider.cs, line 12 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBID0p2-VrUretOx1Cq:-KBID0p3S3X-ryFHGKwO:-236932215) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/Common.Metadata/Model/IIdentityProvider.cs#L12)):*
let's rename to `Get`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Comment by denisivan0v** [comment]
Let's close questions above and then continue

**Comment by rechkalov** [comment]
Review status: 5 of 38 files reviewed at latest revision, 7 unresolved discussions.

---

*[Common.Metadata/Model/IAggregateEntity.cs, line 3 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBIJbIPAXX0J0KLFaFe:-KBIQ-Z7aBcMEo1RedGB:-658613519) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/Common.Metadata/Model/IAggregateEntity.cs#L3)):*
No. See IAggregateRoot.

---

*[Common.Metadata/Model/IdentityExtensions.cs, line 14 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBII_2GtgpqdCeoHlwZ:-KBIQV4j1FVpsFRVpWAv:-487139696) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/Common.Metadata/Model/IdentityExtensions.cs#L14)):*
No, we dont. This methods create a new Expression for provider and key(s), so it's named 'Create'. Any better suggestions?

---

*[Common.Metadata/Model/IdentityExtensions.cs, line 14 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBIJDqkacT6HTCKJUgK:-KBIQPrUDnhq9rodtM0R:136840058) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/Common.Metadata/Model/IdentityExtensions.cs#L14)):*
Where is the problem? All public extension methods have this restriction.

---

*[Common.Metadata/Model/IdentityExtensions.cs, line 26 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBIJ3wxmQAlcvpZBJSp:-KBIR1H2a24ko3rJND2M:-761054369) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/Common.Metadata/Model/IdentityExtensions.cs#L26)):*
We need it. Contact entity does not.

---

*[Common.Metadata/Model/IdentityProviderBase.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBIFAlh2pOV1CBg8mL4:-KBIROnWHRfm5Uj3gopv:45584162) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/Common.Metadata/Model/IdentityProviderBase.cs#L11)):*
See NuClear.Model.Common.IdentityBase. Similar situation here.

---

*[Common.Metadata/Model/IIdentityProvider.cs, line 7 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBIDFEGSvyGqXMZs3sd:-KBLgTx5Xvkj158MwT3R:5174689) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/Common.Metadata/Model/IIdentityProvider.cs#L7)):*
ok

---

*[Common.Metadata/Model/IIdentityProvider.cs, line 12 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBID0p2-VrUretOx1Cq:-KBLbCDD2D-j83SNo6mz:1148703811) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/Common.Metadata/Model/IIdentityProvider.cs#L12)):*
The word "get" is too general. It is good for property getters (if your languge dont have ones). It does not assume any computations (though they are possible). Have you better suggestions?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Comment by maximpashuk** [comment]
Reviewed 9 of 39 files at r1, 5 of 9 files at r2, 85 of 85 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[Replication/Replication.Core/FindSpecificationProvider.cs, line 30 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBltQc1SKs2uKKZy77U:-KBltQc1SKs2uKKZy77V:5468641) ([raw file](https://github.com/2gis/nuclear-river/blob/b4679263a16eecc5b53a51c7adf87db22edc4535/Replication/Replication.Core/FindSpecificationProvider.cs#L30)):*
Я бы вынес в private static field чтобы каждый раз не находить MethodInfo для Enumerable.Contains

---

*[Replication/Replication.Core/Aggregates/AggregateFindSpecificationProvider.cs, line 22 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBlueo4zLsYlT57kyLI:-KBlueo4zLsYlT57kyLJ:-1675305933) ([raw file](https://github.com/2gis/nuclear-river/blob/b4679263a16eecc5b53a51c7adf87db22edc4535/Replication/Replication.Core/Aggregates/AggregateFindSpecificationProvider.cs#L22)):*
кодировка поехала

---

*[Replication/Replication.Core/Aggregates/DirectlyDependentEntityFeatureProcessor.cs, line 13 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBlv2uByi63ljp9Tnad:-KBlv2uByi63ljp9Tnae:-1675305933) ([raw file](https://github.com/2gis/nuclear-river/blob/b4679263a16eecc5b53a51c7adf87db22edc4535/Replication/Replication.Core/Aggregates/DirectlyDependentEntityFeatureProcessor.cs#L13)):*
кодировка поехала

---

*[Replication/Replication.Core/Aggregates/ValueObjectFindSpecificationProvider.cs, line 21 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBlvLkO_BfLOBQINT8J:-KBlvLkO_BfLOBQINT8K:-1675305933) ([raw file](https://github.com/2gis/nuclear-river/blob/b4679263a16eecc5b53a51c7adf87db22edc4535/Replication/Replication.Core/Aggregates/ValueObjectFindSpecificationProvider.cs#L21)):*
кодировка поехала

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Comment by rechkalov** [comment]
Review status: 88 of 95 files reviewed at latest revision, 8 unresolved discussions.

---

*[Replication/Replication.Core/FindSpecificationProvider.cs, line 30 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBltQc1SKs2uKKZy77U:-KBm33O0e6-Ja34LWzaG:-1807276671) ([raw file](https://github.com/2gis/nuclear-river/blob/b4679263a16eecc5b53a51c7adf87db22edc4535/Replication/Replication.Core/FindSpecificationProvider.cs#L30)):*
Это можно, но взятие MethodInfo - это далеко не самая дорогая операция. Более правильный путь на мой взгляд - дополнительный кеширующий слой. Но с ним пока не тороплюсь.

---

*[Replication/Replication.Core/Aggregates/AggregateFindSpecificationProvider.cs, line 22 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KBlueo4zLsYlT57kyLI:-KBm4-Q_TmZtCnrNBPwz:1804397330) ([raw file](https://github.com/2gis/nuclear-river/blob/b4679263a16eecc5b53a51c7adf87db22edc4535/Replication/Replication.Core/Aggregates/AggregateFindSpecificationProvider.cs#L22)):*
Исправил.

Она не поехала. Это какой-то из инструментов упорно создаёт новые файлы в cp1251. Чистки репозитория, конечно, дают результат, но это не решение.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Comment by maximpashuk** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Comment by denisivan0v** [comment]
Reviewed 3 of 9 files at r2, 7 of 85 files at r3, 1 of 16 files at r6.
Review status: 80 of 91 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Common.Metadata/Model/IIdentityProvider.cs, line 7 \[r6\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXnOmVwhZk2dh9A_V_:-KDXnOmWNbdlgCc8nvUP:651743522) ([raw file](https://github.com/2gis/nuclear-river/blob/5910a001031834e59f69a2334a96e05f6d522afc/Common.Metadata/Model/IIdentityProvider.cs#L7)):*
Давай все же если писать xml-комментарии, то на английском

---

*[Common.Metadata/Model/IIdentityProvider.cs, line 12 \[r6\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXnk2_6Y5ZrM1W6ghu:-KDXnk2aoPc_6-SAZYk0:869265797) ([raw file](https://github.com/2gis/nuclear-river/blob/5910a001031834e59f69a2334a96e05f6d522afc/Common.Metadata/Model/IIdentityProvider.cs#L12)):*
Меня смущает `ExtractIdentity` как название метода. 
Мы тут получаем выражение, из которого получаем функцию, которая уже получает значение идентификатора для конкретного типа `TIdentifiable`. 

У меня два варианта - либо придумать название, отражающее суть, которое скорее всего будет длинноватым, либо просто - `Get`, т.к. по возвращаемому типу видно, что именно get

---

*[Common.Metadata/Model/IdentityExtensions.cs, line 12 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXphe-5zkViQTOCABD:-KDXphe0sfFhnbiusbsQ:-1029929245) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/Common.Metadata/Model/IdentityExtensions.cs#L12)):*
Все методы отсюда используется только в тестах. Предлагаю их туда и переместить.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Comment by rechkalov** [comment]
Review status: 75 of 91 files reviewed at latest revision, 5 unresolved discussions.

---

*[CustomerIntelligence/Tests/CustomerIntelligence.Replication.Tests/IdentityExtensions.cs, line 12 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXphe-5zkViQTOCABD:-KDXwJ7d2qAW3znfZ-hL:655756799) ([raw file](https://github.com/2gis/nuclear-river/blob/fb265c5da2176af2a31f25af4f7d2c38a4fe45f6/CustomerIntelligence/Tests/CustomerIntelligence.Replication.Tests/IdentityExtensions.cs#L12)):*
Так ведь это и есть сборка с тестами?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Comment by denisivan0v** [comment]
Reviewed 6 of 39 files at r1, 1 of 9 files at r2, 56 of 85 files at r3, 7 of 7 files at r4, 11 of 16 files at r6, 5 of 5 files at r7, 5 of 5 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Common.Metadata/Features/IndirectlyDependentEntityFeature.cs, line 20 \[r6\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXtGCn_4zguXPmmqQn:-KDXtGCn_4zguXPmmqQo:1910122080) ([raw file](https://github.com/2gis/nuclear-river/blob/5910a001031834e59f69a2334a96e05f6d522afc/Common.Metadata/Features/IndirectlyDependentEntityFeature.cs#L20)):*
`DependentEntitySpecProvider` тогда

---

*[Common.Metadata/Model/Operations/ICommandFactory.cs, line 5 \[r6\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXsJCaSjICshQIzbhl:-KDXsJCaSjICshQIzbhm:-1807268999) ([raw file](https://github.com/2gis/nuclear-river/blob/5910a001031834e59f69a2334a96e05f6d522afc/Common.Metadata/Model/Operations/ICommandFactory.cs#L5)):*
`ICommandFactory<in TKey>`

---

*[CustomerIntelligence/CustomerIntelligence.Domain/Model/CI/Statistics.cs, line 6 \[r6\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXtlB1gUhUpoz5EMFU:-KDXtlB1gUhUpoz5EMFV:1499427090) ([raw file](https://github.com/2gis/nuclear-river/blob/5910a001031834e59f69a2334a96e05f6d522afc/CustomerIntelligence/CustomerIntelligence.Domain/Model/CI/Statistics.cs#L6)):*
Довольно странное название + свойства этого класса нигде не используются

---

*[Replication/Replication.Core/IFindSpecificationProvider.cs, line 10 \[r6\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXyFPsgMADN90QgA74:-KDXyFPtfvB0-LA4Y-iW:807659001) ([raw file](https://github.com/2gis/nuclear-river/blob/5910a001031834e59f69a2334a96e05f6d522afc/Replication/Replication.Core/IFindSpecificationProvider.cs#L10)):*
Не понятно наличие этого интерфейса и класса `FindSpecificationProvider` , который его не имплементирует. 
Чисто по синтаксису - если сделать `FindSpecification<T> Create<TCommand>(IEnumerable<TCommand> commands);`, то вроде все проще

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Comment by denisivan0v** [comment]
Reviewed 3 of 85 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Comment by rechkalov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Common.Metadata/Features/IndirectlyDependentEntityFeature.cs, line 20 \[r6\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXtGCn_4zguXPmmqQn:-KDY3duI3AnmDV4965gG:5205889) ([raw file](https://github.com/2gis/nuclear-river/blob/5910a001031834e59f69a2334a96e05f6d522afc/Common.Metadata/Features/IndirectlyDependentEntityFeature.cs#L20)):*
ок

---

*[Common.Metadata/Model/Operations/ICommandFactory.cs, line 5 \[r6\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXsJCaSjICshQIzbhl:-KDY3u1YwqEdc_M6l2DJ:803436145) ([raw file](https://github.com/2gis/nuclear-river/blob/5910a001031834e59f69a2334a96e05f6d522afc/Common.Metadata/Model/Operations/ICommandFactory.cs#L5)):*
Cчитаю, что данная фича тут не требуется. возможно, будет вредна.
Поясняю: допустим, что есть два ключа: class A, class B : A и есть сущность Entity с ключом B. Использование для неё ICommandFactory<A> в общем случае недопустимо.

---

*[CustomerIntelligence/CustomerIntelligence.Domain/Model/CI/Statistics.cs, line 6 \[r6\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXtlB1gUhUpoz5EMFU:-KDY5PmRTa8I9SXJhy0M:1499568644) ([raw file](https://github.com/2gis/nuclear-river/blob/5910a001031834e59f69a2334a96e05f6d522afc/CustomerIntelligence/CustomerIntelligence.Domain/Model/CI/Statistics.cs#L6)):*
Это сущность-корень агрегата, включающего данные по статистике и прогнозам. Переименовал/переместил.
С ним много непоняток (взяли задачу на этот спринт), но даже в таком виде он упрощает жизнь.

---

*[Replication/Replication.Core/IFindSpecificationProvider.cs, line 10 \[r6\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXyFPsgMADN90QgA74:-KDY9Mh170isoLhw0SE9:-1059886694) ([raw file](https://github.com/2gis/nuclear-river/blob/5910a001031834e59f69a2334a96e05f6d522afc/Replication/Replication.Core/IFindSpecificationProvider.cs#L10)):*
Метод Create<TCommand> невозможен, ибо по текущей генеральной линии обобщение команд не допускается.
Класс `FindSpecificationProvider` выполняет схожую задачу, но имеет другой контракт. Если есть предложения по переименованию - давай.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Comment by denisivan0v** [comment]
Reviewed 7 of 7 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Replication/Replication.Core/IFindSpecificationProvider.cs, line 10 \[r6\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXyFPsgMADN90QgA74:-KDYFNvdTGeg5Ye7UNxL:1572277103) ([raw file](https://github.com/2gis/nuclear-river/blob/5910a001031834e59f69a2334a96e05f6d522afc/Replication/Replication.Core/IFindSpecificationProvider.cs#L10)):*
Договорились устно еще дотюнить

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Comment by rechkalov** [comment]
Review status: 84 of 92 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Replication/Replication.Core/IFindSpecificationProvider.cs, line 10 \[r6\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXyFPsgMADN90QgA74:-KDYM7SILv4eRjsp-Bjz:-1238223067) ([raw file](https://github.com/2gis/nuclear-river/blob/5910a001031834e59f69a2334a96e05f6d522afc/Replication/Replication.Core/IFindSpecificationProvider.cs#L10)):*
Дотюнил

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Comment by denisivan0v** [comment]
Reviewed 8 of 8 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Replication/Replication.Core/IFindSpecificationProvider.cs, line 10 \[r6\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXyFPsgMADN90QgA74:-KDbFHvW9BzkRwgjRB9L:144137422) ([raw file](https://github.com/2gis/nuclear-river/blob/5910a001031834e59f69a2334a96e05f6d522afc/Replication/Replication.Core/IFindSpecificationProvider.cs#L10)):*
Давай переименуем `TConstaint` -> `TCommand`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Comment by rechkalov** [comment]
Review status: 91 of 92 files reviewed at latest revision, 1 unresolved discussion.

---

*[Replication/Replication.Core/IFindSpecificationProvider.cs, line 10 \[r6\]](https://reviewable.io:443/reviews/2gis/nuclear-river/38#-KDXyFPsgMADN90QgA74:-KDbGmXmhC3Y4ike-yLZ:972903091) ([raw file](https://github.com/2gis/nuclear-river/blob/5910a001031834e59f69a2334a96e05f6d522afc/Replication/Replication.Core/IFindSpecificationProvider.cs#L10)):*
Ограничением может выступать не только команда, мы договорились привести этот интерфейс к форме, которая может быть использована для `FindSpecificationProvider`

Опечатку исправил.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Comment by denisivan0v** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Comment by denisivan0v** [comment]
Reviewed 3 of 4 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/38)*

**Pull request merged**
