### PR TITLE
Made exception messages more decriptive & more

### PR DESCRIPTION
**Pull request by rechkalov**
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/134)

### CODE REVIEW

**Comment by denisivan0v** [comment]
Reviewed 11 of 13 files at r1, 1 of 1 files at r2.
Review status: 12 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[StateInitialization/StateInitialization.Core/Actors/BulkReplicationActor.cs, line 128 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/134#-KR87KOerYMAik9dYSVZ:-KR87KOerYMAik9dYSV_:bpo9luj) ([raw file](https://github.com/2gis/nuclear-river/blob/26405ba08faf07beea6a579593291d0e4f102a84/StateInitialization/StateInitialization.Core/Actors/BulkReplicationActor.cs#L128)):*
> ReplaceDataObjectsInBulkCommand
Если truncate отдельно, тогда название команды и актора стоит поменять на `InsertDataObjectsInBulkCommand`

---

*[StateInitialization/StateInitialization.Core/Actors/IndexManagementService.cs, line 11 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/134#-KR88jl2yOTDssDp8-Ia:-KR88jl2yOTDssDp8-Ib:b-mjo3c0) ([raw file](https://github.com/2gis/nuclear-river/blob/26405ba08faf07beea6a579593291d0e4f102a84/StateInitialization/StateInitialization.Core/Actors/IndexManagementService.cs#L11)):*
> ```Smalltalk
> namespace NuClear.StateInitialization.Core.Actors
> {
>     public sealed class IndexManagementService
> ```

Давай просто `IndexManager`. Сервисов и так слишком много ;)

---

*[StateInitialization/StateInitialization.Core/Actors/ReplaceDataObjectsInBulkActor.cs, line 56 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/134#-KR899oVjcq1jNTod-zc:-KR899oVjcq1jNTod-zd:bn2zqcj) ([raw file](https://github.com/2gis/nuclear-river/blob/26405ba08faf07beea6a579593291d0e4f102a84/StateInitialization/StateInitialization.Core/Actors/ReplaceDataObjectsInBulkActor.cs#L56)):*
> ```Smalltalk
>                     sqlText = linq2DBQuery?.SqlText;
>                 }
>                 catch (Exception innerException)
> ```

Какое тут может быть исключение?

---

*[StateInitialization/StateInitialization.Core/Factories/ReplaceDataObjectsInBulkActorFactory.cs, line 22 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/134#-KR89d3HZLlX16lMwb5Q:-KR89d3HZLlX16lMwb5R:bgs74le) ([raw file](https://github.com/2gis/nuclear-river/blob/26405ba08faf07beea6a579593291d0e4f102a84/StateInitialization/StateInitialization.Core/Factories/ReplaceDataObjectsInBulkActorFactory.cs#L22)):*
> ```Smalltalk
>              where !type.IsAbstract && @interface.IsGenericType && @interface.GetGenericTypeDefinition() == typeof(IStorageBasedDataObjectAccessor<>)
>              select new { GenericArgument = @interface.GetGenericArguments()[0], Type = type })
>                 .GroupBy(x => x.GenericArgument, x => x.Type)
> ```

Вопрос дизайна: зачем нам несколько объектов-акссесоров для одного объекта данных? 

Спрашиваю в предположении, что для каждого объекта данных мы выполняем очистку таблицы и потом bulk insert. Если в этом кейсе смаппим два объекта данных на одну таблицу, то получим, что выполнится truncate, потом заполнятся часть атрибутов, затем опять truncate и вторая часть атрибутов. В результате - некорректное состояние. Не очень удобно.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/134)*

**Comment by denisivan0v** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/134)*

**Comment by rechkalov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[StateInitialization/StateInitialization.Core/Actors/BulkReplicationActor.cs, line 128 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/134#-KR87KOerYMAik9dYSVZ:-KRCCu0hMkZB0xsadw3g:bhkz1nv) ([raw file](https://github.com/2gis/nuclear-river/blob/26405ba08faf07beea6a579593291d0e4f102a84/StateInitialization/StateInitialization.Core/Actors/BulkReplicationActor.cs#L128)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> > ReplaceDataObjectsInBulkCommand
> Если truncate отдельно, тогда название команды и актора стоит поменять на `InsertDataObjectsInBulkCommand`
</details>
Согласен.

---

*[StateInitialization/StateInitialization.Core/Actors/IndexManagementService.cs, line 11 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/134#-KR88jl2yOTDssDp8-Ia:-KRCCxTvXineBRZRc7ux:bhkz1nv) ([raw file](https://github.com/2gis/nuclear-river/blob/26405ba08faf07beea6a579593291d0e4f102a84/StateInitialization/StateInitialization.Core/Actors/IndexManagementService.cs#L11)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Давай просто `IndexManager`. Сервисов и так слишком много ;)
</details>
Согласен.

---

*[StateInitialization/StateInitialization.Core/Actors/ReplaceDataObjectsInBulkActor.cs, line 56 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/134#-KR899oVjcq1jNTod-zc:-KRCD1oR_FBWkT7e14GE:b-82hso0) ([raw file](https://github.com/2gis/nuclear-river/blob/26405ba08faf07beea6a579593291d0e4f102a84/StateInitialization/StateInitialization.Core/Actors/ReplaceDataObjectsInBulkActor.cs#L56)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Какое тут может быть исключение?
</details>
Например, linq2db кидает исключение, когда не может по выражению построить sql-запрос (при обращении к полю SqlText).

---

*[StateInitialization/StateInitialization.Core/Factories/ReplaceDataObjectsInBulkActorFactory.cs, line 22 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/134#-KR89d3HZLlX16lMwb5Q:-KRCDV9joG3IkdWeHTFD:b-hlj9gm) ([raw file](https://github.com/2gis/nuclear-river/blob/26405ba08faf07beea6a579593291d0e4f102a84/StateInitialization/StateInitialization.Core/Factories/ReplaceDataObjectsInBulkActorFactory.cs#L22)):*
<details><summary><i>Previously, denisivan0v (Denis Ivanov) wrote…</i></summary>
> Вопрос дизайна: зачем нам несколько объектов-акссесоров для одного объекта данных? 
> 
> Спрашиваю в предположении, что для каждого объекта данных мы выполняем очистку таблицы и потом bulk insert. Если в этом кейсе смаппим два объекта данных на одну таблицу, то получим, что выполнится truncate, потом заполнятся часть атрибутов, затем опять truncate и вторая часть атрибутов. В результате - некорректное состояние. Не очень удобно.
</details>
Именно потому truncate вынесен отдельной операций, после него - заполнение.
Конкретный пример - сущность ValidationResult из контекста VR. Есть много выражений для её построения, объединить их через union в одно - невозможно, поэтому требуется каждое выполнить последовательно.

PS. Речь не про последовательное заполнение атрибутов сущности, а про наличие нескольких источников одного типа.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/134)*

**Comment by denisivan0v** [comment]
Reviewed 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[StateInitialization/StateInitialization.Core/Actors/BulkInsertDataObjectsActor.cs, line 56 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/134#-KR899oVjcq1jNTod-zc:-KRCdrQf3B1JVu1IG004:b32w1t) ([raw file](https://github.com/2gis/nuclear-river/blob/26405ba08faf07beea6a579593291d0e4f102a84/StateInitialization/StateInitialization.Core/Actors/BulkInsertDataObjectsActor.cs#L56)):*
<details><summary><i>Previously, rechkalov (a.rechkalov) wrote…</i></summary>
> Например, linq2db кидает исключение, когда не может по выражению построить sql-запрос (при обращении к полю SqlText).
</details>
Ok

---

*[StateInitialization/StateInitialization.Core/Factories/ReplaceDataObjectsInBulkActorFactory.cs, line 22 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/134#-KR89d3HZLlX16lMwb5Q:-KRCe2P5dbKOmbzIttqe:b32w1t) ([raw file](https://github.com/2gis/nuclear-river/blob/26405ba08faf07beea6a579593291d0e4f102a84/StateInitialization/StateInitialization.Core/Factories/ReplaceDataObjectsInBulkActorFactory.cs#L22)):*
<details><summary><i>Previously, rechkalov (a.rechkalov) wrote…</i></summary>
> Именно потому truncate вынесен отдельной операций, после него - заполнение.
> Конкретный пример - сущность ValidationResult из контекста VR. Есть много выражений для её построения, объединить их через union в одно - невозможно, поэтому требуется каждое выполнить последовательно.
> 
> PS. Речь не про последовательное заполнение атрибутов сущности, а про наличие нескольких источников одного типа.
</details>
Ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/134)*

**Pull request merged**
