### PR TITLE
Добавил случайные постфиксы к именам временных баз

### PR DESCRIPTION
**Pull request by rechkalov**
ping @maximpashuk @denisivan0v

[Review on Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/24)

### CODE REVIEW

**Comment by denisivan0v** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/StringExtensions.cs, line 6 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/24#-K9BQtwopUqSfQdbUcpM:-K9BQtwopUqSfQdbUcpN:1262611707) ([raw file](https://github.com/2gis/nuclear-river/blob/b7736a14651f7f43d44fe879d5e23c1de09a594f/CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/StringExtensions.cs#L6)):*
Let's rename `StringExtensions` class to something related to connection strings. Or maybe it shouldn't be an extension method to `string`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/24)*

**Comment by rechkalov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/StringExtensions.cs, line 6 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/24#-K9BQtwopUqSfQdbUcpM:-K9BThV0ggBmMXwPO7Kx:1066576725) ([raw file](https://github.com/2gis/nuclear-river/blob/b7736a14651f7f43d44fe879d5e23c1de09a594f/CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/StringExtensions.cs#L6)):*
Это расширение к типу string (потому что по сути другого нет), Поскольку это расширение к string, то и находится оно в StringExtensions. Поскольку расширение достаточно специфично, оно сделано как internal. Назначение метода полностью отражено в его имени.

Не вижу обоснованных причин что-то менять.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/24)*

**Comment by maximpashuk** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/24)*

**Comment by denisivan0v** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/StringExtensions.cs, line 6 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/24#-K9BQtwopUqSfQdbUcpM:-K9C6Sgi8-WStr0S2HzZ:-422387831) ([raw file](https://github.com/2gis/nuclear-river/blob/b7736a14651f7f43d44fe879d5e23c1de09a594f/CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/StringExtensions.cs#L6)):*
internal - значит может быть использовано кем угодно внутри сборки. В общем, я бы сделал приватный метод внутри класса. К `string` все это не имеет вообще никакого отношения.

code smell - очень веская причина изменений

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/24)*

**Comment by rechkalov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/StringExtensions.cs, line 6 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/24#-K9BQtwopUqSfQdbUcpM:-K9CC3Ef9PChNooRwfnt:1672053847) ([raw file](https://github.com/2gis/nuclear-river/blob/b7736a14651f7f43d44fe879d5e23c1de09a594f/CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/StringExtensions.cs#L6)):*
code smell усилится при помещении этого метода внутри класса (был у меня такой промежуточный шаг), ведь это не его ответственность.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/24)*

**Comment by denisivan0v** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/StringExtensions.cs, line 6 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/24#-K9BQtwopUqSfQdbUcpM:-K9CDXiFCzwLb4MF_uZ_:1712229527) ([raw file](https://github.com/2gis/nuclear-river/blob/b7736a14651f7f43d44fe879d5e23c1de09a594f/CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/StringExtensions.cs#L6)):*
Не согласен. Название `RunnerConnectionStringSettings` как бы намекает, что он настривает connection string-и. А то, что они каждый раз должны меняться -  именно деталь реализации

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/24)*

**Comment by rechkalov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/StringExtensions.cs, line 6 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/24#-K9BQtwopUqSfQdbUcpM:-K9CIx0plrSeXx8jqaSy:-670346919) ([raw file](https://github.com/2gis/nuclear-river/blob/b7736a14651f7f43d44fe879d5e23c1de09a594f/CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/StringExtensions.cs#L6)):*
Он не настраивает, а только предоставляет доступ к настройкам. См ConnectionStringSettingsAspect.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/24)*

**Comment by denisivan0v** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/StringExtensions.cs, line 6 \[r1\]](https://reviewable.io:443/reviews/2gis/nuclear-river/24#-K9BQtwopUqSfQdbUcpM:-K9R9ArCv84vHSJoBY5f:248718742) ([raw file](https://github.com/2gis/nuclear-river/blob/b7736a14651f7f43d44fe879d5e23c1de09a594f/CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/StringExtensions.cs#L6)):*
Ок, предоставляет доступ. Перефразирую тогда: то, что настройки, к которым предоставляется доступ, каждый раз должны меняться - именно деталь реализации

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/24)*

**Comment by denisivan0v** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/2gis/nuclear-river/24)*

**Pull request merged**
