### PR TITLE
Replication based on actor model

### LINKED ISSUE #61: Decouple Replication component infrastructure and the Windows service host
As the result we'll be able to reference Replication component as nupkg in different hosts

### PR DESCRIPTION
**Pull request by denisivan0v**
closes #61

---
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river/71)

### CODE REVIEW

**Comment by denisivan0v** [comment]
@maximpashuk @rechkalov take a look

**Comment by maximpashuk** [comment]
Review status: 0 of 604 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitAccumulator.cs, line 33 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVruJ415roB4osSk_Y:-KGVruJ5SyqKprbGh4EO:1243435073) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitAccumulator.cs#L33)):*
Мне кажется проверка на null не нужна, мы же ниже добавляем в коллекцию через if(tryparse) только хорошие значения.

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Specifications/Specs.Map.Facts.AggregateIdentity.cs, line 1 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVViZsmnd9jnk1Tqr2:-KGVViZsmnd9jnk1Tqr3:1924175958) ([raw file](https://github.com/2gis/nuclear-river/blob/f7a91f0ac9d79d29b4bdafc04fc6a5c1fd017554/CustomerIntelligence/CustomerIntelligence.Replication/Specifications/Specs.Map.Facts.AggregateIdentity.cs#L1)):*
Я бы растащил содержимое всего этого класса по соответствующим accessors.
Каждый метод здесь это получается приватный метод accessor.

---

*[Replication/Replication.Core/Actors/DataObjectsActorBase.cs, line 12 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVY-t_OEZG-sNdxO6Q:-KGVY-t_OEZG-sNdxO6R:-2135532608) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/Replication/Replication.Core/Actors/DataObjectsActorBase.cs#L12)):*
Мне кажется можно не держать private ссылку на IQuery .
Map spec providers её держат через замыкания.

---

*[Replication/Tests/Replication.Core.Tests/Replication.Core.Tests.csproj, line 59 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVmGkhufrwGfumUQsS:-KGVmGkiXUGhpzI0tX5s:1489734240) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/Replication/Tests/Replication.Core.Tests/Replication.Core.Tests.csproj#L59)):*
Ссылка на querying.metadata лишняя и не нужна вообще.
+ 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/71)*

**Comment by denisivan0v** [comment]
Review status: 0 of 604 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitAccumulator.cs, line 33 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVruJ415roB4osSk_Y:-KGVtddWqSsO5uxKtr_H:1004126563) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitAccumulator.cs#L33)):*
Согласен

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Specifications/Specs.Map.Facts.AggregateIdentity.cs, line 1 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVViZsmnd9jnk1Tqr2:-KGVtw6YiusxKdQma6fD:71074353) ([raw file](https://github.com/2gis/nuclear-river/blob/f7a91f0ac9d79d29b4bdafc04fc6a5c1fd017554/CustomerIntelligence/CustomerIntelligence.Replication/Specifications/Specs.Map.Facts.AggregateIdentity.cs#L1)):*
Согласен. Даже пробовал это делать. Оставлял для мержей.
Если ничего тут менять в других ветках не планируем, растащу

---

*[Replication/Replication.Core/Actors/DataObjectsActorBase.cs, line 12 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVY-t_OEZG-sNdxO6Q:-KGVuLgR5TXOMpoSnOiF:1004126563) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/Replication/Replication.Core/Actors/DataObjectsActorBase.cs#L12)):*
Согласен

---

*[Replication/Tests/Replication.Core.Tests/Replication.Core.Tests.csproj, line 59 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVmGkhufrwGfumUQsS:-KGVuRyGzLyqa-1OC6n3:1004126563) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/Replication/Tests/Replication.Core.Tests/Replication.Core.Tests.csproj#L59)):*
Согласен

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/71)*

**Comment by maximpashuk** [comment]
Review status: 0 of 604 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Replication/Replication.OperationsProcessing/Transports/CorporateBus/CorporateBusMessage.cs, line 21 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVuUdwhQE0TkMtuVeg:-KGVuUdxpi1EfE4yEPd5:-782956326) ([raw file](https://github.com/2gis/nuclear-river/blob/f7a91f0ac9d79d29b4bdafc04fc6a5c1fd017554/Replication/Replication.OperationsProcessing/Transports/CorporateBus/CorporateBusMessage.cs#L21)):*
Тут был enumerable по аналогии с классами ServiceBus, чтобы абстракции не растекались.
Я бы уточнил у ивана, нормально ли так. Эти классы вообще бы перенести в messaging репозиторий.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/71)*

**Comment by rechkalov** [comment]
Review status: 0 of 604 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs, line 46 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGWYEMWBWtFKsxsAJPB:-KGWYEMX_-5G5qIDSmdx:-761546125) ([raw file](https://github.com/2gis/nuclear-river/blob/a11f68ceb2bb63ae5de8bf7c33685150cc842590/CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs#L46)):*
Мне очень не нравится идея события RelatedDataObjectOutdatedEvent, typeof(Firm) не мог стать outdated, поскольку это объект из фактов.
Честнее будет сказать, что у объекта Account изменилось поле-ссылка FirmId. И пофиг, на что именно оно ссылается, на фирму или на заказ - это уже знание уровня агрегатов.
Второй вариант - сказать, что изменилась связь между двумя фактами, Account и Firm. Это тоже вполне вписывается на уровень etl1

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectDeletedEvent.cs, line 9 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGWSW6i7aLUrxYnsLm5:-KGWSW6i7aLUrxYnsLm6:-452924318) ([raw file](https://github.com/2gis/nuclear-river/blob/a11f68ceb2bb63ae5de8bf7c33685150cc842590/CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectDeletedEvent.cs#L9)):*
Предлагаю убрать Type из события. Даже ERM отказалась от использования clr-типов в событиях.

---

*[Replication/Replication.Core/Actors/SyncDataObjectsActor.cs, line 61 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGWUFEot2Cs5zoeHSK9:-KGWUFEq5XTMUUGLAwM6:-1200823384) ([raw file](https://github.com/2gis/nuclear-river/blob/a11f68ceb2bb63ae5de8bf7c33685150cc842590/Replication/Replication.Core/Actors/SyncDataObjectsActor.cs#L61)):*
По всем аналогичным местам: требуется корректно расставить генерацию событий. При удалении - сначала события, потом удаления. При создании - наоборот. При обновлении - так и остаётся.

---

*[StateInitialization/StateInitialization.Core/BulkReplicationActor.cs, line 39 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVVk0tGUiuuFcl9XJ2:-KGVVk0u93bvR40ghdnO:-1652429982) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/StateInitialization/StateInitialization.Core/BulkReplicationActor.cs#L39)):*
Какой эффект от AsParallel().AsOrdered() здесь?

---

*[StateInitialization/StateInitialization.Core/Commands/ReplaceDataObjectsInBulkCommand.cs, line 8 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVmHicSjRsujeIHQWO:-KGVmHidGiMl5pVxq6pj:444960877) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/StateInitialization/StateInitialization.Core/Commands/ReplaceDataObjectsInBulkCommand.cs#L8)):*
Почему бы команде не указывать, какие именно типы дата-объектов подлежат переносу? Это позволит избавиться от IDataObjectTypesProvider. А типы можно не хард-кодить, а получать из IEntityTypeMappingRegistry<IDomain> - там есть полный перечень.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/71)*

**Comment by denisivan0v** [comment]
Review status: 0 of 604 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs, line 46 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGWYEMWBWtFKsxsAJPB:-KGuXHST_LacCrR1flji:55457896) ([raw file](https://github.com/2gis/nuclear-river/blob/a11f68ceb2bb63ae5de8bf7c33685150cc842590/CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs#L46)):*
Так и есть. RelatedDataObjectOutdatedEvent(relatedDataObjectType, relatedDataObjectId) - событие о том, что изменилось поле-ссылка FirmId. И тут мы точно знаем, что это ссылка на Firm. Вроде все честно

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectDeletedEvent.cs, line 9 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGWSW6i7aLUrxYnsLm5:-KGuXrXb_QTEiobkrvdR:660792847) ([raw file](https://github.com/2gis/nuclear-river/blob/a11f68ceb2bb63ae5de8bf7c33685150cc842590/CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectDeletedEvent.cs#L9)):*
Знание о типе необходимо. 
Здесь нет ничего плохого от использования Type, т.к. это тип внутри конкретного bounded context-а. Даже с точки зрения .NET используются те же сборки. Это high cohesion

Про ERM другая история. Там нет знания о том, в каком bounded context-е будет обрабатываться event, поэтому потребовался дексрипторный интерфейс `IEntityType`. Это low coupling

---

*[Replication/Replication.OperationsProcessing/Transports/CorporateBus/CorporateBusMessage.cs, line 21 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVuUdwhQE0TkMtuVeg:-KGuZ_txNHvzG3SJx_Ir:-1417495315) ([raw file](https://github.com/2gis/nuclear-river/blob/f7a91f0ac9d79d29b4bdafc04fc6a5c1fd017554/Replication/Replication.OperationsProcessing/Transports/CorporateBus/CorporateBusMessage.cs#L21)):*
С абстракциями все ок. `MessageBase` - это абстракция.
Все ее реализации как раз и обладают частными знаниями о транспорте. Для корпоративной шины - это `CorporateBusPackage` и он один. В нем уже несколько объектов единого формата

---

*[StateInitialization/StateInitialization.Core/BulkReplicationActor.cs, line 39 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVVk0tGUiuuFcl9XJ2:-KGu_LykaVncak-6_p_8:997917587) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/StateInitialization/StateInitialization.Core/BulkReplicationActor.cs#L39)):*
На будущее, чтобы отсвечивало.

---

*[StateInitialization/StateInitialization.Core/Commands/ReplaceDataObjectsInBulkCommand.cs, line 8 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVmHicSjRsujeIHQWO:-KGu_f35VvuLDNmIskvD:-1683272230) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/StateInitialization/StateInitialization.Core/Commands/ReplaceDataObjectsInBulkCommand.cs#L8)):*
`IEntityTypeMappingRegistry`-  интеграционная абстракция от ERM. Причем для интеграции по event-ам.
В River нет смысла ее использовать дальше OperationProcessing сборки

По поводу указывать в команде, какие именно типы дата-объектов подлежат переносу. Думал об этом вначале. Тут проблема в том, что будет возможность ошибиться, указав неверный connection string для какого-либо из типов дата-объектов при создании команды. 
`IDataObjectTypesProvider` как раз и хорош тем, что отдает набор типов дата-объектов, для которых применима команда

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/71)*

**Comment by denisivan0v** [comment]
Review status: 0 of 604 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[Replication/Replication.Core/Actors/SyncDataObjectsActor.cs, line 61 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGWUFEot2Cs5zoeHSK9:-KGvSz58aNVYPZT0N7fE:-499146009) ([raw file](https://github.com/2gis/nuclear-river/blob/a11f68ceb2bb63ae5de8bf7c33685150cc842590/Replication/Replication.Core/Actors/SyncDataObjectsActor.cs#L61)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/71)*

**Comment by rechkalov** [comment]
Review status: 0 of 605 files reviewed at latest revision, 6 unresolved discussions.

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs, line 46 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGWYEMWBWtFKsxsAJPB:-KGzVI2ey0afoCtYN-fq:1258736895) ([raw file](https://github.com/2gis/nuclear-river/blob/a11f68ceb2bb63ae5de8bf7c33685150cc842590/CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs#L46)):*
Тогда, может честно и написать, что изменилась ссылка? DataObjectReferenceChangedEvent(From: typeof(Account), FromId: account.Id, To: typeof(Firm), ToId: account.FirmId)

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectDeletedEvent.cs, line 9 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGWSW6i7aLUrxYnsLm5:-KGzWzUcTTV1yVciOpIW:-481013762) ([raw file](https://github.com/2gis/nuclear-river/blob/a11f68ceb2bb63ae5de8bf7c33685150cc842590/CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectDeletedEvent.cs#L9)):*
Знание - нужно, но о типе ли? Давай посмотрим, как используется это знание. Этот тип анализируется в аккумуляторе etl2. Получается, что etl2 зависит от etl1. Я же предлагаю, чтобы etl1 использовал некий компонент, и etl2 тоже использовал его. Это dependency invertion :D

Впрочем, ладно. Пусть остаётся как есть.

---

*[Replication/Replication.Core/Actors/SyncDataObjectsActor.cs, line 61 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGWUFEot2Cs5zoeHSK9:-KGzZmtZtfdCwFwjf2Nx:1166483628) ([raw file](https://github.com/2gis/nuclear-river/blob/a11f68ceb2bb63ae5de8bf7c33685150cc842590/Replication/Replication.Core/Actors/SyncDataObjectsActor.cs#L61)):*
Тут, похоже, возникло непонимание:

При удалении:
events.AddRange(_dataChangesHandler.HandleRelates(toDelete)); // Пока объекты ещё в базе, определяем зависимости
events.AddRange(_dataChangesHandler.HandleDeletes(toDelete)); // Пока объекты ещё в базе, определяем "прямые" зависимости
 _bulkRepository.Delete(toDelete); // Больше объектов в базе нет
events.AddRange(_dataChangesHandler.HandleRelates(toDelete)); // Объектов уже нет, зависимости определить невозможно. Это, получается лишний вызов

При создании:
 events.AddRange(_dataChangesHandler.HandleRelates(toCreate)); // Объектов ещё нет, поэтому и зависимости определить невозможно. Это лишний вызов.
_bulkRepository.Create(toCreate); // Объекты появились
events.AddRange(_dataChangesHandler.HandleRelates(toCreate)); // Объекты уже есть, зависимости можно вычислить, 
events.AddRange(_dataChangesHandler.HandleCreates(toCreate)); // но логически событие "в клиенте №1 изменилась ссылка на фирму №2" не должно возникать до события "создан клиент №1", поэтому последние две строчки лучше поменять местами.

Опять-же: технически всё ок. Работать будет. Но пахнет.

---

*[StateInitialization/StateInitialization.Core/BulkReplicationActor.cs, line 39 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVVk0tGUiuuFcl9XJ2:-KGzbPOLvN-yGOlfxZyY:-1368752580) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/StateInitialization/StateInitialization.Core/BulkReplicationActor.cs#L39)):*
Лучше замени на комментарий. А то кто-нибудь поверит.

---

*[StateInitialization/StateInitialization.Core/Commands/ReplaceDataObjectsInBulkCommand.cs, line 8 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVmHicSjRsujeIHQWO:-KGzcmW4jvvn4yp8PMQv:-1618440376) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/StateInitialization/StateInitialization.Core/Commands/ReplaceDataObjectsInBulkCommand.cs#L8)):*
> IEntityTypeMappingRegistry - интеграционная абстракция от ERM. Причем для интеграции по event-ам

Это - реестр сущностей, объектов данных. С событиями или интеграцией он не связан. 
Он может использоваться для решения интеграционных вопросов, но так же он может быть использован в любом месте, где потребуется, это нормально. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/71)*

**Comment by rechkalov** [comment]
Review status: 0 of 605 files reviewed at latest revision, 6 unresolved discussions.

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectDeletedEvent.cs, line 9 \[r5\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGzgwWw6HAvY07Mlb7Z:-KGzgwWw6HAvY07Mlb7_:-1179071113) ([raw file](https://github.com/2gis/nuclear-river/blob/76f89bf7d8cc4eaa41aac3fdeecf01c512884a24/CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectDeletedEvent.cs#L9)):*
Предлагаю заменить long на TDataObjectId, это всё-равно потребуется делать для VR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/71)*

**Comment by denisivan0v** [comment]
Review status: 0 of 616 files reviewed at latest revision, 5 unresolved discussions.

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs, line 46 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGWYEMWBWtFKsxsAJPB:-KH-Kra4eoM_kxNLgcPF:1144069201) ([raw file](https://github.com/2gis/nuclear-river/blob/a11f68ceb2bb63ae5de8bf7c33685150cc842590/CustomerIntelligence/CustomerIntelligence.Replication/Accessors/AccountAccessor.cs#L46)):*
Речь же идет не о ссылке, а о поле-ссылке. Это не БД, тут другая семантика.

Суть ивента в том, что при его возникновении нельзя доверять состоянию объекта, с которым (как-то) связан объект, к которому была применена команда. Поэтому и параметры ивента - тип и идентификатор "протухшего" объекта. Ну и название отсюда же

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectDeletedEvent.cs, line 9 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGWSW6i7aLUrxYnsLm5:-KH-FSeAVTif1tYUXFR_:-499146009) ([raw file](https://github.com/2gis/nuclear-river/blob/a11f68ceb2bb63ae5de8bf7c33685150cc842590/CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectDeletedEvent.cs#L9)):*
Done.

---

*[CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectDeletedEvent.cs, line 9 \[r5\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGzgwWw6HAvY07Mlb7Z:-KH-FTUZkrumX6eAL8CK:-1977248982) ([raw file](https://github.com/2gis/nuclear-river/blob/76f89bf7d8cc4eaa41aac3fdeecf01c512884a24/CustomerIntelligence/CustomerIntelligence.Replication/Events/DataObjectDeletedEvent.cs#L9)):*
В каждом контексте свои команды. В VR будут свои конкретные команды, обобщения тут ни к чему

---

*[Replication/Replication.Core/Actors/SyncDataObjectsActor.cs, line 61 \[r3\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGWUFEot2Cs5zoeHSK9:-KH-Ns9K_wDlW3KcEuNi:1232145480) ([raw file](https://github.com/2gis/nuclear-river/blob/a11f68ceb2bb63ae5de8bf7c33685150cc842590/Replication/Replication.Core/Actors/SyncDataObjectsActor.cs#L61)):*
Согласен, погорячился

---

*[StateInitialization/StateInitialization.Core/BulkReplicationActor.cs, line 39 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVVk0tGUiuuFcl9XJ2:-KH-HKr4_hhG8ks_FEm-:-579618882) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/StateInitialization/StateInitialization.Core/BulkReplicationActor.cs#L39)):*
Поверит чему? 
`AsOrdered()` возвращает ` OrderingQueryOperator` ([код](http://referencesource.microsoft.com/#System.Core/System/Linq/Parallel/QueryOperators/Options/OrderingQueryOperator.cs,0e0e205770b05c74)), который имплементирует IEnumerable. Все честно

---

*[StateInitialization/StateInitialization.Core/Commands/ReplaceDataObjectsInBulkCommand.cs, line 8 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVmHicSjRsujeIHQWO:-KH-JnqZ5oyMfgHE2-Ym:1884693090) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/StateInitialization/StateInitialization.Core/Commands/ReplaceDataObjectsInBulkCommand.cs#L8)):*
>  он может быть использован в любом месте, где потребуется

Согласен. Вопрос лишь в целесообразности. 
Тут овчинка выделки не стоит, кейс очень простой, нет смысла его усложнять и добавлять зависимости.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/71)*

**Comment by rechkalov** [comment]
Review status: 0 of 616 files reviewed at latest revision, 1 unresolved discussion.

---

*[StateInitialization/StateInitialization.Core/BulkReplicationActor.cs, line 39 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVVk0tGUiuuFcl9XJ2:-KH-Od29uxxGKLMYQF69:-1479328276) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/StateInitialization/StateInitialization.Core/BulkReplicationActor.cs#L39)):*
Поверит, что тут есть какая-то параллельность. Или ещё какая-то магия, требующая AsParallel. Сейчас тут нет никакой параллельности, значит и AsParallel не должно быть. Если она нужна - то есть тикеты и todo-комментарии.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/71)*

**Comment by denisivan0v** [comment]
Review status: 0 of 616 files reviewed at latest revision, 1 unresolved discussion.

---

*[StateInitialization/StateInitialization.Core/BulkReplicationActor.cs, line 39 \[r2\]](https://reviewable.io:443/reviews/2gis/nuclear-river/71#-KGVVk0tGUiuuFcl9XJ2:-KH-fBPRFDiU2Eb8DKIe:1012348637) ([raw file](https://github.com/2gis/nuclear-river/blob/d7f1f58c594117e62dd538090192ac1998f1d883/StateInitialization/StateInitialization.Core/BulkReplicationActor.cs#L39)):*
Все по процессу https://github.com/2gis/nuclear-river/issues/76

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/71)*

**Comment by rechkalov** [comment]
Reviewed 1 of 8 files at r7.
Review status: 1 of 616 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/71)*

**Comment by maximpashuk** [comment]
Reviewed 760 of 827 files at r1, 17 of 24 files at r2, 6 of 13 files at r4, 30 of 36 files at r5, 32 of 32 files at r6, 8 of 8 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/71)*

**Comment by maximpashuk** [comment]
Reviewed 3 of 827 files at r1, 11 of 11 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river/71)*

**Pull request merged**
